### PR TITLE
Sikuli Fix #463,#468

### LINKED ISSUE #463: Sikuli doesn't work after switching between profiles
Steps to reproduce:
- Create two user profiles A and B
- Define a simple Sikuli command, e.g. an *export_window* function in *test.sikuli* which clicks on the windows symbol bottom left
- Start Dragon, select profile A. The *test window* command works
- Terminate Dragon
- Start Dragon, select profile B. The *test window* command works
- Terminate Dragon
- Start Dragon, select either profile A or B. As before the *test window* command works. Switch the user profile from A to B or B to A respectively. 
Now the *test window* command isn't recognized anymore. I expected it to work.
No errors are shown in the Natlink or Sikuli Server window.

Use case: I'd like to use Sikuli commands to switch easily between a German and an English profile.

Do you think the problem is to be located within Sikuli or Caster?

Specs:
Sikuli 1.4
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

### LINKED ISSUE #464: Sikuli Timeout
From time to time after executing a Sikuli command via Caster I get the errors below. Afer that Sikuli commands don't work anymore. Unfortunately, I can't give an example command which always generates this error. I don't experience a consistency in this.

Error Natlink window:
```
<class 'socket.timeout'>
timed out
<traceback object at 0x0EF108A0>
  File "C:\dev\Natlink-User\Caster\castervoice\asynch\sikuli\sikuli.py", line 52, in execute
    fn()

  File "C:\dev\Python27\Lib\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)

  File "C:\dev\Python27\Lib\xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose

  File "C:\dev\Python27\Lib\xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)

  File "C:\dev\Python27\Lib\xmlrpclib.py", line 1313, in single_request
    response = h.getresponse(buffering=True)

  File "C:\dev\Python27\Lib\httplib.py", line 1121, in getresponse
    response.begin()

  File "C:\dev\Python27\Lib\httplib.py", line 438, in begin
    version, status, reason = self._read_status()

  File "C:\dev\Python27\Lib\httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)

  File "C:\dev\Python27\Lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
```

Error Sikuli server window:
```
Exception happened during processing of request from ('127.0.0.1', 60764)
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\SocketServer.py", line 659, in __init__
    self.finish()
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\SocketServer.py", line 718, in finish
    self.wfile.close()
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\_socket.py", line 2009, in close
    self.flush()
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\_socket.py", line 2036, in flush
    self._sock.sendall(chunk)
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\_socket.py", line 1484, in send
    return super(ChildSocket, self).send(data)
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\_socket.py", line 382, in handle_exception
    return method_or_function(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\_socket.py", line 382, in handle_exception
    return method_or_function(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\_socket.py", line 1200, in send
    self._handle_channel_future(future, "send")
  File "C:\Users\User\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\_socket.py", line 384, in handle_exception
    raise _map_exception(jlx)
error: [Errno 10054] Socket closed
```
Anyone who experiences this as well? Any idea?

Specs:
Sikuli 1.4
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

### PR DESCRIPTION
**Pull request by seekM**
Fix #463 by reloading `sikuli.py` and #468 whose root cause was that the grammar for controlling Sikuli was [overriden](https://github.com/dictation-toolbox/Caster/blob/develop/castervoice/asynch/sikuli/sikuli.py#L64-L65) instead of extended. In the process of the fix I restructured `sikuli.py` a bit. What's not so elegant is that when a profile change occurs the old grammar isn't unloaded. However, at the moment I can't think of real disadvantages this could constitute in practice. I couldn't make the `refresh sick you Lee` command work, but replaced it by `terminate sick server` and `launch sick server`. It's only one more command and achieves the same thing.

Note that this doesn't fix #464. As described in this issue: Whenever you expect something to happen which isn't happening (e.g. the Sikuli server window stays black or doesn't change, a command isn't executed which should work) focus the Sikuli server window and press a key. Don't get confused by the error messages wich appear in both windows.

I tested this PR by doing the following:
- Open one profile
- Call one of your custom commands presented in the Sikuli server window which works (e.g. one which clicks on the Windows symbol)
- Call one of your custom commands which doesn't work (e.g. because the image to look for is not visible)
- Launch Sikuli's IDE by voice: `launch sick IDE`
- Terminate the Sikuli server: `terminate sick server`
- Create new Sikuli scripts
- Launch the Sikuli server: `launch sick server`
- Test the new commands
- Terminate the server, remove the new commands, start the server, check that the removed commands don't work anymore
- Switch your user profile, repeat the steps above

### CODE REVIEW

**Comment by LexiconCode** [comment]
A very simple refresh command you could simply use the dragonflies [playback](https://dragonfly2.readthedocs.io/en/latest/actions.html?#playback-action) action. Basically tying together the two commands  "launch sick server" and "terminate sick server".

Example
```Python
from dragonfly import Playback
        'minimize':
            R(Playback([(["minimize", "window"], 0.0)]), rdescript="Minimize Window"),
```

Thus far everything has worked as expected so great work!

**Comment by seekM** [comment]
I just tried this but ran into a problem similar to the one I encountered when I tried to implement this command: When you experience #464 with `terminate sick server` (i.e. you'd have to hit a key in the Sikuli server window such that the command proceeds) but don't press the key in time before `launch sick server` is started, an additional Sikuli server windows in created, but closed due to a failure. Then you a press a key in the old Sikuli server window which then is closed too. This leads to a state in which I wasn't always able to launch a new Sikuli server. I there recommend to terminate and start manually and make sure that the server is terminated successfully before starting a new one.

**Comment by LexiconCode** [comment]
So this implementation seems to work on my end but let me know what you think. The pause in between the functions of ensures that there is enough time between between terminating and starting the server.

`'refresh sick': Function(terminate_sick_command) + Pause("100") + Function(bootstrap_start_server_proxy),`

**Comment by seekM** [comment]
I think two seconds isn't long enough to realize that the server isn't terminating properly and that you have to press a key before the new server is started. This is especially true if you haven't kept in mind that this might happen and are suprised by this. I think it should be at least `Pause("600")` (six seconds).

**Comment by LexiconCode** [comment]
Sounds good, I'll see if I can find a more reliable method to terminate the server as it seems to be the crux of the issue.

**Comment by LexiconCode** [comment]
I'll add rdescripts and merge for now and we can leave it as is until another pull request.

**Pull request merged**
