### PR TITLE
Cleaned and fixed default bringme paths

### PR DESCRIPTION
**Pull request by TTeig**
# Cleaned and fixed default bringme paths

## Description
Fixed broken discord link.
Changed to use settings.settings() for most default bringme paths instead of duplicating.

## Motivation and Context
Bring me commands for Discord and Log.txt didn't work.

## How Has This Been Tested
Manually testing all the bringme commands.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue or bug)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Renamed existing command phrases (we discourage this without a strong rationale).

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] My code implements all the features I wish to merge in this pull request.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [x] Code is clear and readable.

### CODE REVIEW

**Comment by LexiconCode** [comment]
Looks like CCRModulesTestCase failed to initialize.
```
======================================================================

ERROR: test_instantiation (rules.ccr.test_rule_modules.CCRModulesTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):
  File "c:\users\travis\build\dictation-toolbox\caster\tests\test_util\modules_testing.py", line 37, in test_instantiation
    rule_class()
  File "c:\users\travis\build\dictation-toolbox\caster\castervoice\rules\ccr\recording_rules\bringme.py", line 48, in __init__
    super(BringRule, self).__init__(settings.settings(["paths", "SM_BRINGME_PATH"]))
  File "c:\users\travis\build\dictation-toolbox\caster\castervoice\lib\merge\selfmod\selfmodrule.py", line 33, in __init__
    self._deserialize()
  File "c:\users\travis\build\dictation-toolbox\caster\castervoice\rules\ccr\recording_rules\bringme.py", line 89, in _deserialize
    self._smr_extras.extend(self._rebuild_items())
  File "c:\users\travis\build\dictation-toolbox\caster\castervoice\rules\ccr\recording_rules\bringme.py", line 99, in _rebuild_items
    for header, section in config_copy.items()
  File "c:\users\travis\build\dictation-toolbox\caster\castervoice\rules\ccr\recording_rules\bringme.py", line 98, in <dictcomp>
    for key, value in section.items()})
  File "C:\Python27\lib\ntpath.py", line 331, in expandvars
    if '$' not in path and '%' not in path:
TypeError: argument of type 'bool' is not iterable
```

**Comment by TTeig** [comment]
I can take a look again tomorrow, but if I don't get it to work right away I'll make a PR with just the discord and log paths fixed so that's done.

**Comment by LexiconCode** [comment]
Sounds good, If you force push to your branch you can overwrite the changes that you don't want.

**Comment by TTeig** [comment]
Whoops. Ended up closing it and now there's a new one. #783

**Pull request closed without merging**
