### PR TITLE
add CCR rule to Chrome 

### PR DESCRIPTION
**Pull request by alexboche**

### CODE REVIEW

**Comment by LexiconCode** [comment]
Go ahead and update the documentation and we will get this tested and merged.

**Comment by alexboche** [comment]
It took me 20 minutes to update two lines of the documentation. is there an easier way to do it? Multiple cursor seemed to help when I was editing the last column but not when I was editing the first column.

**Comment by LexiconCode** [comment]
> It took me 20 minutes to update two lines of the documentation. is there an easier way to do it? Multiple cursor seemed to help when I was editing the last column but not when I was editing the first column.

Originally when I started working with the markdown tables I found it very cumbersome with formatting. Still not perfect but a big chunk of my time originally was trying to maintain the formatting of the columns. Fortunately there are linters that can beautify the columns.

**Comment by alexboche** [comment]
> > It took me 20 minutes to update two lines of the documentation. is there an easier way to do it? Multiple cursor seemed to help when I was editing the last column but not when I was editing the first column.
> 
> Originally when I started working with the markdown tables I found it very cumbersome with formatting. Still not perfect but a big chunk of my time originally was trying to maintain the formatting of the columns. Fortunately there are linters that can beautify the columns. Do you think that will help with the issues you're facing?

Yes what was taking a long time was that when I inserted a
somewhere all of the other lines became misaligned including the pipe bars. can you point me to such a tool that beautifies the columns?

**Comment by LexiconCode** [comment]
> 
> 
> > > It took me 20 minutes to update two lines of the documentation. is there an easier way to do it? Multiple cursor seemed to help when I was editing the last column but not when I was editing the first column.
> > 
> > 
> > Originally when I started working with the markdown tables I found it very cumbersome with formatting. Still not perfect but a big chunk of my time originally was trying to maintain the formatting of the columns. Fortunately there are linters that can beautify the columns. Do you think that will help with the issues you're facing?
> 
> Yes what was taking a long time was that when I inserted a
> somewhere all of the other lines became misaligned including the pipe bars. can you point me to such a tool that beautifies the columns?

I would recommend the following extension for VS code.
https://marketplace.visualstudio.com/items?itemName=darkriszty.markdown-table-prettify

Some of the tables look improperly formatted but due to their table size they won't display correctly in VS code but are perfectly fine when on gethub. As for writing new tables and   rows this extension makes it really straightforward and simple.

**Comment by alexboche** [comment]
So this pull request is done and tested as far as I'm concerned.

**Comment by mrob95** [comment]
Pull request is fine but conflicts with #530, which significantly alters the structure of app grammars. I will reimplement this once #530 is merged.

**Pull request merged**
