### PR TITLE
Key commands tweaks

### PR DESCRIPTION
**Pull request by alexboche**
(I consider this ready for review now.)
## Description

* This adds the ability to say shin/que dunce/sauce wally to press control shift end/home. shin/que do exactly the same thing as each other in this case. Technically this is unnecessary, because you can already say que lease/ross wally to get this but it is nice cognitively to have this option.
* I also change latch-> lairch (home) ratch->rairch (end) because of a pattern of misrecognition. 
Edit: 
* I also removed four commands blitch/flitch/brick/frick which I previously added without proper testing, two of which caused misrecognitions (brick/frick).
* I removed unnecessary repeats after the commands "sauce wally": R(Key("c-home")),
        "dunce wally": R(Key("c-end")),
        "(shin | que) sauce wally": R(Key("cs-home")),
        "(shin | que) dunce wally": R(Key("cs-end")),
though kept the repeat after [shin] lease/ross wally because that can be used in Lyx and less frequently in VS code.
 Newly added/removed commands have not yet been documented and (I assume) have not been adopted by other users so there should be no harm done. 

## Related Issue
Regarding the names of commands, #625 is related.

## Motivation and Context
Shorter commands are useful instead of Ross/lease wally and that's what lairch/rairch are for. Ideally I think most command should have a version that's easy to remember and a shorter version (usually one syllable). A while back, I commented out the original master command for lease/ross/que/shin/fly/wally and replaced it with individual commands attempting to preserve the original commands as well. I am not sure if shin sauce/dunce wally was part of that or not since they are somewhat redundant but they are included there now in any case. 

## How Has This Been Tested
I have been using the commands lairch/rairch (as well as the previously added bird/firch) heavily for several days with no misrecognitions. I was using these when testing the commands from #669 and did not notice any misrecognitions. I only tested the shin/que sauce/dunce wally a couple times. 

## Types of changes

- [ ] (possibly) documentation change
- [ ] Bug fix (non-breaking change which fixes an issue or bug)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Renamed existing command phrases (we discourage this without a strong rationale).

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] I have checked for and utilized existing command phrases from within Caster (delete if not applicable). 
- [x] My code implements all the features I wish to merge in this pull request.
- [x] My change requires a change to the documentation (but maybe not yet).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

### CODE REVIEW

**Comment by kendonB** [comment]
Hi Alex, are you able to use the PR template? My view is that all PRs should use it except for trivial changes. For example, a typo fix or a single line change is trivial but something that needs more than a sentence to explain is not trivial and should use the template.

**Comment by mrob95** [comment]
```
        "(lease wally | lairch) [<nnavi10>]": R(Key("home:%(nnavi10)s")),
        "(ross wally | rairch) [<nnavi10>]": R(Key("end:%(nnavi10)s")),
        "sauce wally [<nnavi10>]": R(Key("c-home:%(nnavi10)s")),
        "dunce wally [<nnavi10>]": R(Key("c-end:%(nnavi10)s")),
        "(shin | que) sauce wally [<nnavi10>]": R(Key("cs-home:%(nnavi10)s")),
        "(shin | que) dunce wally [<nnavi10>]": R(Key("cs-end:%(nnavi10)s")),
        "bird [<nnavi500>]": R(Key("c-left:%(nnavi500)s")),
        "firch [<nnavi500>]": R(Key("c-right:%(nnavi500)s")),
        "brick [<nnavi500>]": R(Key("s-left:%(nnavi500)s")),
        "frick [<nnavi500>]": R(Key("s-right:%(nnavi500)s")),
        "blitch [<nnavi500>]": R(Key("cs-left:%(nnavi500)s")),
        "flitch [<nnavi500>]": R(Key("cs-right:%(nnavi500)s"))
```

A few points.

1. There is no need for repeat values on "wally" commands, they are idempotent.
2. Is any of this stuff documented anywhere?
3. Don't these cause all sorts of misrecognitions, particularly combined with others like #669? (I'm not using caster master so haven't tested, but the fact that they keep needing to be tweaked suggests that this is a problem)

This may be a discussion better had in #625, but I think it needs to be had. I'm not sure it's fair or reasonable to expect new users (who may have poor quality audio setups or be using less accurate backends) to learn a whole load of made up words which all sound similar and aren't documented.

**Comment by alexboche** [comment]
The "wally" are not always itempotent (i.e. repeating them sometimes does do something different than just doing them once) for example in Lyx. These are not documented yet, because there still kind of experimental, but it is nice to build a say things like "shin lairch" instead of "shin lease wally" since its shorter. Yeah maybe a bunch of new shorter commands should all be added at the same time and documented rather than a few at a time like I've been doing. I have had success with these without misrecognitions so far but I've only tested for a few days.

**Comment by LexiconCode** [comment]
I think we need to be careful about adding new commands that have made of words so perhaps we should have a discussion about this issue in #625. Overwhelming amounts of made up words can be a deterrent for adoption as well.

Then we can address this issue after the CCR rewrite? BTW which is very close to being In a testable usable state.

**Comment by LexiconCode** [comment]
Will be invalidated by merger of the rewrite. Reopen under a new pull request.

**Pull request closed without merging**
