### PR TITLE
Preliminary Python 3 Support

### PR DESCRIPTION
**Pull request by mrob95**
Definitely unfinished but a start. I have chased down all failing tests on both versions and have ensured that caster loads without errors (on kaldi at least). I haven't done any testing of commands though and this will need to be done, particularly for the GUI elements. There will be bugs remaining. Feel free to commit to this branch.

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [ ] My code implements all the features I wish to merge in this pull request.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

### CODE REVIEW

**Comment by Versatilus** [comment]
What are your thoughts on using `future` versus using `six`? I like the aesthetics of `future`, but I realize there are some corner cases involving the fact their `str` is a different class rather than an alias for the built-in one.

**Comment by mrob95** [comment]
Yeah future may be nicer, I am used to six from dragonfly but it would not be much work to switch. I think there is something to be said for imports being explicit but the simplicity of future may be worth it. 

Automated tests are failing at the moment due to linting getting confused by the imports, so it may also fix that.

**Comment by Versatilus** [comment]
I believe you might have to add comments to turn off the linter for those lines.

**Comment by LexiconCode** [comment]
I'm about to commit to do just that.

**Comment by Versatilus** [comment]
I'm open to doing what everyone else wants to do. One point to using `six` is that all of the changes will be quite obvious, so it will be easy to do some sort of automated replacement when we're ready to leave Python 2 behind.

**Comment by mrob95** [comment]
I have the Natlink module building and loading with py3, now it is just a matter of trawling through a few thousand lines of 20 year old python and we'll be getting somewhere.

**Comment by LexiconCode** [comment]
> 
> 
> I'm open to doing what everyone else wants to do. One point to using `six` is that all of the changes will be quite obvious, so it will be easy to do some sort of automated replacement when we're ready to leave Python 2 behind.

I would be leaning towards six versus future given my limited experience porting. That seems like a valid point for transitioning later on.

> 
> 
> I have the Natlink module building and loading with py3, now it is just a matter of trawling through a few thousand lines of 20 year old python and we'll be getting somewhere.

Well that's great news that it's moving forward!

**Comment by LexiconCode** [comment]
I read rebased on the latest master and had to force push. I don't like how it's changed the commit history perhaps there's a better way?

**Comment by mrob95** [comment]
For a public branch like this I would definitely favour just `git merge master`

**Comment by LexiconCode** [comment]
Yes I'm unfamiliar with working with PR's with multiple contributors. Perhaps you could force Push your branch to reset the history to its original state.

**Comment by mrob95** [comment]
My branch isn't up to date so we would lose your changes, I think it's fine to leave it as it is. I used to use rebase quite a lot and it is good for some things, but more and more I think just merging is preferable.

**Comment by LexiconCode** [comment]
Waiting on next release Dragonfly/kaldi-active-grammar to include fixes. Subsequent further testing will continue at that point.

**Comment by LexiconCode** [comment]
I'm going to merge this pull request.

- It's becoming a pain keep up with merge conflicts.
- Some radical changes to the GUI or upcoming
- I have not had any issues on Python 2 

Acknowledge further testing on Python 3 especially for the MouseGrid's. However that can take place in the future pull request.

**Pull request merged**
