### PR TITLE
fix: failing `Set up Python` step

### LINKED ISSUE #945: `Set up Python` step in `Caster Lint/Unit Tests / python 2 windows (2.7.x) (push)` fails

### PR DESCRIPTION
**Pull request by hamirmahal**
# fix: failing `Set up Python` step

## Related Issue

This pull request fixes #945.

## Motivation and Context

The `Set up Python` step fails on the main branch. This pull request fixes that by using a different `action`.

## How Has This Been Tested

CI

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] My code implements all the features I wish to merge in this pull request.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
.

**Comment by LexiconCode** [comment]
Thank you so much for helping out with the project. Sorry I haven't gotten back to you in a more timely manner. My time has been limited and involved upstream in Natlink/NalinkCore

The reason it fails is because of the redistributable isn't available through Microsoft and only retrievable through the way back time machine.

I had a generous individual for a time host the package. Unfortunately the host is no longer available.
https://github.com/dictation-toolbox/Caster/blob/master/.github%2FInstall-VCForPython27.ps1#L49

Since official support has stopped with Python 2.7 I'm inclined to drop the test all together. I would still leave a branch up with 2.7 accessible code but without further support.

If you'd like to contribute further go to 'PyDrop2' branch for most of the recent work is committed. I run into a bit of an issue with QT dropping support for python 32-bit. 

If you would like to connect and chat further I'm all for supporting any level of contributing.

**Comment by hamirmahal** [comment]
You're welcome!

**Comment by hamirmahal** [comment]
I'm spread a bit thin at the moment; I'm not sure if there are any other areas where I can contribute immediately. But, I'll open another pull request if I see something I might be able to improve.

**Pull request closed without merging**
