### PR TITLE
Add Changelog

### PR DESCRIPTION
**Pull request by LexiconCode**
Any feedback would be appreciated. This works in conjunction with the github release feature.

### CODE REVIEW

**Comment by kendonB** [comment]
This is very cool! How did you do this, btw? Not manually, I hope?

**Comment by LexiconCode** [comment]
> This is very cool! How did you do this, btw? Not manually, I hope?

[GitHub Changelog Generator](https://github.com/github-changelog-generator/github-changelog-generator)

Two things to note. In order to get it to work with Windows. You're going to need to create a empty folder on your C drive named `tmp`. Commandline example `github_changelog_generator -u dictation-toolbox -p Caster -t <Personal OAuth token>` The second Generating OAuth token allows you to bypass the rate limiting of github at 60 requests per hour.

Good question would be how to add more tags or custom tags.

**Comment by LexiconCode** [comment]
All right we need to figure out a way to tie this into Travis build system.

**Comment by LexiconCode** [comment]
Will reevaluate after CCR merge

**Comment by LexiconCode** [comment]
Viable alternative that can be local and through Travis
https://www.npmjs.com/package/auto-changelog

**Pull request merged**
