### PR TITLE
New command to scroll mouse wheel continuously

### PR DESCRIPTION
**Pull request by dusty-phillips**
# New command to scroll mouse wheel continuously

## Description

Initiate scrolling as an asynchronous action until the user says `cancel`.

command is `zinc sauce|dunce <speed>` where speed is one of super slowly, slowly, normal, fast and superfast.

## Motivation and Context

I got tired of saying "scree dunce" repeatedly when I didn't know how far I wanted to scroll.
The existing `<direction> <time_in_seconds>` command does a similar thing, except that it moves the cursor while doing so.
The VSCode "scroll up/down" and "scroll page down/up" commands do a similar thing in that they don't move the cursor, but they do not operate continuously.

I chose the name zinc because it seems unique and Dragon is good at picking up the `z` sound.

## How Has This Been Tested

I have tested the new command in VS code and chrome. In both cases it initiated scrolling in the correct direction and cancelled appropriately. I have only tested using Dragon

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue or bug)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Renamed existing command phrases (we discourage this without a strong rationale).

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] I have checked for and utilized existing command phrases from within Caster (delete if not applicable). 
- [x] My code implements all the features I wish to merge in this pull request.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [x] New documentation is clear and complete.
- [x] Code is clear and readable.

### CODE REVIEW

**Comment by kendonB** [comment]
@dusty-phillips is there any reason not to use `scree` here? That would be more consistent with the other command.

**Comment by kendonB** [comment]
I have tested this and it seems to work on kaldi.

**Comment by kendonB** [comment]
I have tested this and it seems to work on DPI15.

**Comment by kendonB** [comment]
One other request: are you able to import the spec from `castervoice.rules.ccr.standard`? This really should have been done long ago for the other one as well. Would be great to change the other one also while we're at it.

**Comment by dusty-phillips** [comment]
I went one further and replaced "cancel" with SymbolSpecs.CANCEL for all async actions. I can undo the others if necessary.

**Comment by dusty-phillips** [comment]
Note: This is failing with the "cancel" changes. I didn't test last night. 😳 I'm not sure why, though.

**Comment by LexiconCode** [comment]
I will test this out tomorrow and see if I can reproduce your issue.

**Comment by LexiconCode** [comment]
> 
> 
> Note: This is failing with the "cancel" changes. I didn't test last night. 😳 I'm not sure why, though. The problem is that it doesn't. Initiating the command works fine.

`SymbolSpecs.CANCEL` is a spec whereas  "cancel" in the context of an asynchronous action references `rspec` of a registered action.

`rspec` is necessary because a spec can change with simplified transformers/user edited specs.

**Comment by dusty-phillips** [comment]
I removed the problematic commit for now.

**Comment by LexiconCode** [comment]
If this is ready I will merge.

**Comment by dusty-phillips** [comment]
It's been working well for me, I think it's ready.

**Pull request merged**
