### PR TITLE
Add command for alt-click for VS code

### PR DESCRIPTION
**Pull request by dusty-phillips**
#210  Description

Add a command for holding down the Alt key, while clicking the left mouse button.

## Motivation and Context

I use this to specifically for setting the cursor position in the Visual Studio the terminal.

## How Has This Been Tested

I added the command and rebooted Dragon. Then I entered a long line in the terminal, and said `altar kick` while hovering the mouse over the middle of it. The mouse cursor moved to the indicated point as expected.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue or bug)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Renamed existing command phrases (we discourage this without a strong rationale).

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] I have checked for and utilized existing command phrases from within Caster (delete if not applicable). 
- [x] My code implements all the features I wish to merge in this pull request.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

## Maintainer/Reviewer Checklist

- [x] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

### CODE REVIEW

**Comment by LexiconCode** [comment]
I need to test and see how common holding down `Alt key` in other editors. If it's something only utilized in VS Code it would be better in the grammar itself. However I'm pretty sure a few other editors uses behavior but I need to verify.

**Comment by LexiconCode** [comment]
Here are the results from my testing. Take a look at ContextAction in this [issue](https://github.com/dictation-toolbox/Caster/issues/426) and let me know what you think.

**ctr hold left-click**
Atom
Sublime 3

**alt hold left-click**
vs code

**shift alt hold left-click**
Visual Studio 2019

**not supported**
notepad++

**Comment by dusty-phillips** [comment]
This site shows that alt-click is using a fair few applications, although most of them are probably not used by voice recognition enthusiast: https://defkey.com/search?irq=alt-click

So I should just move the mapping to the `VSCodeNonCcrRule`?

**Comment by LexiconCode** [comment]
that's a really useful website! I suppose if you don't mind adding support for those other editors real quick grammar specific?

**Comment by LexiconCode** [comment]
> So I should just move the mapping to the `VSCodeNonCcrRule`?

I think that would be the best approach for now.

**Comment by dusty-phillips** [comment]
Switched to vscode. Note that alt-click is also used in vscode to make multiple selections.

**Pull request merged**
