### PR TITLE
`stun` command for control enter

### PR DESCRIPTION
**Pull request by dusty-phillips**
# `stun` command for control enter

## Description

Insert a ctrl+enter into the editor.

## Motivation and Context

Several applications and web sites use ctrl+enter for inserting a new line without submitting a form or for submitting a form instead of a newline (go figure). I use it in the VSCode commit editor, github input boxes, facebook, and my work chat application.

I chose `stun` for it's analogy to `shock`

## How Has This Been Tested

I've been using it for a while in several applications.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue or bug)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Renamed existing command phrases (we discourage this without a strong rationale).

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] I have checked for and utilized existing command phrases from within Caster (delete if not applicable). 
- [x] My code implements all the features I wish to merge in this pull request.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

Note: I didn't update the documentation because "shock" is only seen in the cheat sheet, and I'm reluctant to change the layout in a LaTeX document.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

### CODE REVIEW

**Comment by LexiconCode** [comment]
Rather than creating another command to remember why not handle the behavior based on context.

```
redo = ContextAction(default=Key("c-y"), actions=[
    # Use cs-z for rstudio
    (AppContext(executable="rstudio"), Key("cs-z")),
])
```

**Comment by dusty-phillips** [comment]
I'm not sure how that would work in this case. In most editors, I want both behaviours available -- for example, in VS code's commit editor, "shock" inserts a new line, but "stun" submits the commit. That's how github's comment editor works on the web as well. On the other hand, in my company's chat program, "shock" submits a single line by default, but if you want to insert a new line, use "stun".

On the other hand, some programs, like slack, use `shift+enter` to insert a new line where `enter` submits the message by default. So are you proposing a "submit" command that would be set to ctrl+enter in vscode, enter in slack, and ctrl+enter in chrome if visiting the github page, wherease a "newline" command would be set to "enter" by default, but "shift+enter" in slack and "ctrl+enter" in if visiting facebook in chrome?

**Comment by kendonB** [comment]
I believe this one is already handled by `fly shock`. We need to have a really good reason to introduce single syllable specs as they are notorious for misrecognition. Please close if you don't disagree.

**Comment by dusty-phillips** [comment]
I wasn't aware that fly worked with shock. now that I see how the modifier choices work, I realize a lot of my own custom commands could be covered by them. Thanks.

**Comment by kendonB** [comment]
@dusty-phillips the docs may not yet reflect the modifiers works that @alexboche did. If that's the case, please feel free to work on it!

**Pull request closed without merging**
