### PR TITLE
Create issue templates

### PR DESCRIPTION
**Pull request by kendonB**

### CODE REVIEW

**Comment by LexiconCode** [comment]
Let's automate some of the creation of the bug reports. 

Imagine saying a command n vscode that doesn't work as expected. 

1. User Says "submit grammar bug report" (different phrases for different types of reports)
2. A bug report is compiled 
- Operating system
- Python version
- Caster Version/Commit # 
- last 20 or x phrases dictated (think the record from history command)
- Current program in the forefront 
- Current grammar/s
- It opens a github issue webpage with the generated template for the end user to edit.

**Comment by LexiconCode** [comment]
I been working on a method record gifs. I could put it up as a pull request as I think I'll need some help finishing it off.

The idea is people can record by voice a gif that's included in the template of their issue.
Often it's hard to visualize what's being described. A visual representation more than the screenshot would be informative.

**Comment by kendonB** [comment]
Do you want to make those changes before putting up any issue template?

**Comment by LexiconCode** [comment]
I'll modify the current issue and remove references to automation. It'll take a while so it's best to keep it separate.

**Comment by LexiconCode** [comment]
We should add including include the complete command phrase word for word to bug reports. This makes it much easier to diagnose when there is no ambiguity.

**Comment by kendonB** [comment]
I have changed the bug report template to include:
```
**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. Go to '...'
2. Say '...'
3. See error
```

**Comment by LexiconCode** [comment]
Thanks @kendonB

**Pull request merged**
