### PR TITLE
Created a few new chrome commands, including click by voice commands.

### PR DESCRIPTION
**Pull request by alexboche**
I'm trying to learn how to do pull requests – this is my 1st one. I have added some new Google Chrome commands including commands for click by voice Chrome extension functionality. I have not tested these on the latest caster release but have tested them on my own system.

### CODE REVIEW

**Comment by LexiconCode** [comment]
Welcome! Looks good so far! I will test this on the development branch in the next few days. 

One thing I would recommend is optimizing command names for contributing back to the repository. The idea is to reduce cognitive load. This is achieved by standardizing commands names across multiple programs by reusing commands that exist elsewhere with the same function. Therefore, it's easier to remember and customize across the whole project.  

```Python
        "nab [<n>]":                    R(Key("c-tab")) * Repeat(extra="n"),
        "lab [<n>]":                    R(Key("cs-tab")) * Repeat(extra="n"),
```
An alternative could be
```Python
        "next tab [<n>]":                    R(Key("c-tab")) * Repeat(extra="n"),
        "previous tab [<n>]":                R(Key("cs-tab")) * Repeat(extra="n"),
```

**Comment by LexiconCode** [comment]
click by voice commands 👍 

You can also add to the documentation to list your new commands. Edit the following file in the chrome section - Application_Commands_Quick_Reference.md](https://github.com/dictation-toolbox/caster/blob/develop/castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md)

**Comment by mrob95** [comment]
People may already be aware of it, but I've got a fair bit of use out of an extension called SurfingKeys, which provides vim-like shortcuts for a lot of browser functionality, including hints for links and input fields, searching through bookmarks, moving the current tab to a new window, and a load of other stuff.

**Comment by LexiconCode** [comment]
Sounds really advanced open a pull request.

**Comment by mrob95** [comment]
It doesn't really need any extra caster stuff to work, since it can all just be done with the phonetic alphabet (foxy brings up hints, which are all just pairs of letters, saying e.g. "x-ray arch" will click that link). Just needs the chrome extension.

**Comment by LexiconCode** [comment]
@alexboche Let me know if you need any help and you can reach me on [Gitter ](https://gitter.im/synkarius/caster?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) as well.

**Comment by LexiconCode** [comment]
duplicate

d6631b03b9d307866c50b22795dc5b4e6a05eddd

**Pull request closed without merging**
