### PR TITLE
add pr template

### PR DESCRIPTION
**Pull request by kendonB**
# This PR uses the proposed template

## Description

This pull request adds a template for adding pull requests.

## Related Issue

None.

## Motivation and Context

Having a template for pull requests helps to add a little discipline to the process and helps to remind contributors what needs to be done before something gets merged.

## How Has This Been Tested

I have done no testing as it needs to be merged in order to test with GitHub.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] My code implements all the features I wish to merge in this pull request.
- [ ] My change requires a change to the documentation.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

### CODE REVIEW

**Comment by LexiconCode** [comment]
That would work pretty well for code PR in the traditional sense. However grammars can be viewed a little differently.

Things to think about for a grammar PR.
- renamed any existing specs? (Typically discouraged if possible without strong rationale.)
- check and utilize existing command names in the creation of their specs?
- check to see if they're duplicating functionality that already exists in the current grammar set provided by Caster?

Should we have PR templates for both code PR's and grammar PR's?

**Comment by kendonB** [comment]
I don't think we have the nice button interface for PRs like we do for issues. We could achieve that with an extra section that people can delete. I think the benefits are worth a bit of extra trouble

**Comment by LexiconCode** [comment]
> 
> 
> I don't think we have the nice button interface for PRs like we do for issues. We could achieve that with an extra section that people can delete. I think the benefits are worth a bit of extra trouble

I think that's a good plan for now.

**Comment by LexiconCode** [comment]
I think two more checkboxes might be helpful to indicate the status of the pull request. It is hard to know as contributors can't tag (unlike maintainers) the pull requests.

#Status
- [ ] WIP
- [ ] Complete

**Comment by kendonB** [comment]
@LexiconCode see if you prefer my latest change to your edit? I incorporated it into the main checklist rather than having it separate and clarified the language a bit.

https://github.com/kendonB/Caster/commit/f21436ec6195bf1147655a6a0ec8c2a7a3b5124d#diff-aabc15087a0ad90f49f516c89602877b

**Comment by kendonB** [comment]
@LexiconCode also review these changes which modifies the pull request template for app grammars as you requested in a concise way.

https://github.com/kendonB/Caster/commit/ba3c8f85ebacdf7d00683f22753ac5b84d83deee#diff-aabc15087a0ad90f49f516c89602877b 

I also deliberately do not use the language "spec" here as it's particularly confusing to newcomers. I like the terms "command phrases" and "command actions" as it's immediately obvious what these terms mean.

**Pull request merged**
