### PR TITLE
[WIP] Caster Quick Reference as restructured text

### LINKED ISSUE #629: Pull everything we can out of CasterQuickReference.tex and add content to ReadTheDocs
LaTeX is hard for newbies to use. LaTeX is hard for people who have used it for years to use (i.e me).

I propose that we pull a lot of the stuff in CQR out and put it into readthedocs.

The big drawback which would prevent us from doing this for everything is that markdown doesn't do footnotes. However, a lot of the current CQR doesn't have footnotes. I don't think being able to nicely print docs on paper is that big a deal now that people can say "bring me X doc page".

It is also possible to hack table footnotes in markdown using superscripts which may also be an option.

### PR DESCRIPTION
**Pull request by und3fined-v01d**
# Title

Caster Quick Reference as restructured text

## Description

This PR is an attempt to convert the existing documentation in the Caster Quick Reference guide from LaTeX to [restructured text](https://docs.restructuredtext.net/index.html)

## Related Issue

Closes #629 

## Motivation and Context

As mentioned in #629, using LaTeX for documentation poses challenge not just for new users but even for seasoned users. We want to replace the existing documentation from LaTeX to a more easy to grasp syntax like markdown or restructured text, both of which are also understood and rendered by Github Markdown as an additional plus

## How Has This Been Tested

This PR has been tested using the [reStructuredText VSCode](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext) extension

OS: Windows 10 Home

This change only affects the docs

## Types of changes

- [x] Docs change / refactoring / dependency upgrade

## Checklist

- [x] I have read the CONTRIBUTING document.
- [ ] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [ ] My code implements all the features I wish to merge in this pull request.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

### CODE REVIEW

**Comment by und3fined-v01d** [comment]
@LexiconCode i tried running Pandoc on the CasterQuickReference.tex file however the formatting seems to not be right since the preview does not get rendered correctly. I have used markdown before but am new to restructured text, could you take a look and help me out?

**Comment by LexiconCode** [comment]
> 
> 
> @LexiconCode i tried running Pandoc on the CasterQuickReference.tex file however the formatting seems to not be right since the preview does not get rendered correctly. I have used markdown before but am new to restructured text, could you take a look and help me out?

I would be glad to take a look. A quick peek at the moment.
[rst.pdf](https://github.com/dictation-toolbox/Caster/files/5996046/rst.pdf)

rendered using [http://rst.ninjs.org](
http://rst.ninjs.org/?theme=basic#Li4gY29udGFpbmVyOjogcGljdHVyZQoKICAgKDI5NywyMTApCgogICAoMTAsMjA1KQoKICAgLi4gcnVicmljOjogQ2FzdGVyIFF1aWNrIFJlZmVyZW5jZQogICAgICA6bmFtZTogY2FzdGVyLXF1aWNrLXJlZmVyZW5jZQogICAgICA6Y2xhc3M6IHVubnVtYmVyZWQKCiAgICgxMCwxOTUpCgogICAuLiBydWJyaWM6OiAuIE51bWJlcnMKICAgICAgOm5hbWU6IG51bWJlcnMKCiAgICAKCiAgIHwgbnVtYiA8MC4uLjFtPiAgKipwcmludCBkaWdpdHMqKgogICB8IHdvcmQgbnVtYmVyIDwwLi4uOT4gICoqcHJpbnQgYXMgd29yZHMqKgoKICAgLi4gcnVicmljOjogLiBBbHBoYWJldAogICAgICA6bmFtZTogYWxwaGFiZXQKCiAgICAKCiAgIC4uIGNvbnRhaW5lcjo6IG11bHRpY29scwoKICAgICAgfCA1IGFyY2gKICAgICAgfCBicm92CiAgICAgIHwgY2hhcgogICAgICB8IGRlbHRhCiAgICAgIHwgZWNobwogICAgICB8IGZveHkKICAgICAgfCBnb29mCiAgICAgIHwgaG90ZWwKICAgICAgfCBpbmRpYQogICAgICB8IGp1bGlhCiAgICAgIHwga2lsbwogICAgICB8IGxpbWEKICAgICAgfCBtaWtlCiAgICAgIHwgbm92YWtlZW4KICAgICAgfCBvc2NhcgogICAgICB8IHByaW1lCiAgICAgIHwgcXVlYmVjCiAgICAgIHwgcm9tZW8KICAgICAgfCBzaWVycmEKICAgICAgfCB0YW5nbwogICAgICB8IHVuaWZvcm0KICAgICAgfCB2aWN0b3IKICAgICAgfCB3aGlza2V5CiAgICAgIHwgeC1yYXkKICAgICAgfCB5YW5rZWUKICAgICAgfCB6dWx1CgogICAgCgogICAuLiBydWJyaWM6OiAuIFB1bmN0dWF0aW9uCiAgICAgIDpuYW1lOiBwdW5jdHVhdGlvbgoKICAgIAoKICAgLi4gcnVicmljOjogLiBDb21wYXJpc29ucwogICAgICA6bmFtZTogY29tcGFyaXNvbnMKCiAgICAKCiAgIHwgW2lzXSBncmVhdGVyIHRoYW4gICoqYGA+YGAqKgogICB8IGxlc3MgdGhhbiAgKipgYDxgYCoqCiAgIHwgZ3JlYXRlciBbdGhhbl0gW29yXSBlcXVhbCBbdG9dICAqKmBgPj1gYCoqCiAgIHwgbGVzcyBbdGhhbl0gW29yXSBlcXVhbCBbdG9dICAqKmBgPD1gYCoqCiAgIHwgZXF1YWwgdG8gICoqYGA9PWBgKioKCiAgICgxMDUsMjAwKQoKICAgLi4gcnVicmljOjogLiBEaXJlY3Rpb25zCiAgICAgIDpuYW1lOiBkaXJlY3Rpb25zCgogICAgCgogICB8IHNhdWNlICAgKip1cCoqCiAgIHwgZHVuY2UgICAqKmRvd24qKgogICB8IGxlYXNlICAgKipsZWZ0KioKICAgfCByb3NzICAgKipyaWdodCoqCgogICAuLiBydWJyaWM6OiAuIEVkaXRpbmcKICAgICAgOm5hbWU6IGVkaXRpbmcKCiAgICAKCiAgIHwgY2xlYXIgICAqKmJrc3BjKioKICAgfCBkZWxpICAgKipkZWwqKgogICB8IHNob2NrICAgKiplbnRlcioqCiAgIHwgY2FuY2VsICAqKmVzY2FwZSoqCiAgIHwgc2F2ZSAgKipjdHJsIC0gcyoqCgogICAuLiBydWJyaWM6OiAuIFNlbGVjdGlvbiwgTW92ZW1lbnQKICAgICAgOm5hbWU6IHNlbGVjdGlvbi1tb3ZlbWVudAoKICAgIAoKICAgfCBzaGFja2xlICAqKnNlbGVjdCBsaW5lKioKICAgfCBzaGluICAgKipzaGlmdCAtIDxkaXI+KioKICAgfCBxdWV1ZSAgICoqY3RybCAtIHNoaWZ0IC0gPGRpcj4qKgogICB8IGZseSAgICoqY3RybCAtIDxkaXI+KioKICAgfCBzcGxhdCAgICoqY3RybCAtIGRlbC9ia3NwYyoqCiAgIHwgd2FsbHkgICoqaG9tZS9lbmQqKgogICB8IHRlbGwgc2luayAgKiplbmQgKyBlbnRlcioqCiAgIHwgdGVsbCBkb2NrICAqKmVuZCArIHNlbWljb2xvbiArIGVudGVyKioKICAgfCBrcmFrZW4gICoqY3RybCArIHNwYWNlKioKICAgfCBodWcgPGVuY2xvc2U+ICAgKiplbmNsb3NlcyB0YXJnZXQqKgoKICAgLi4gcnVicmljOjogLiBDb3B5IGFuZCBQYXN0ZQogICAgICA6bmFtZTogY29weS1hbmQtcGFzdGUKCiAgICAKCiAgIHwgc3Rvb3NoICAgKipjb3B5KioKICAgfCBjdXQgICAqKmN1dCoqCiAgIHwgc3BhcmsgICAqKnBhc3RlKioKICAgfCBnYXJiICAgKipkb3VibGUtY2xpY2sgKyBjb3B5KioKICAgfCBkcm9wICAgKipkb3VibGUtY2xpY2sgKyBwYXN0ZSoqCiAgIHwgZHVwbGUgICAqKmR1cGxpY2F0ZSBsaW5lKioKCiAgICgyMDAsMjAwKQoKICAgLi4gcnVicmljOjogLiBUZXh0IEZvcm1hdHRpbmcKICAgICAgOm5hbWU6IHRleHQtZm9ybWF0dGluZwoKICAgIAoKICAgKipDYXBpdGFsaXNhdGlvbioqCgogICB8IHllbGwgICoqU09NRSBXT1JEUyoqCiAgIHwgdGllICAqKlNvbWUgV29yZHMqKgogICB8IGdlcnJpc2ggICAqKnNvbWVXb3JkcyoqCiAgIHwgc2luZyAgKipTb21lIHdvcmRzKioKICAgfCBsYXdzICAqKnNvbWUgd29yZHMqKgogICB8ICoqU3BhY2luZyoqCiAgIHwgZ3VtIFx8IGd1biAgKipzb21ld29yZHMqKgogICB8IHNwaW5lICAqKnNvbWUtd29yZHMqKgogICB8IHNuYWtlICAgKipzb21lX3dvcmRzKioKICAgfCBwZWJibGUgICoqc29tZS53b3JkcyoqCiAgIHwgaW5jbGluZSAgKipzb21lL3dvcmRzKioKICAgfCBkaXNzZW50IFx8IGRlc2NlbnQgICoqc29tZVx3b3JkcyoqCiAgIHwgQ2FwaXRhbGlzYXRpb24gYW5kIHNwYWNpbmcgY2FuIGJlIGNvbWJpbmVkIGludG8gYSBzaW5nbGUgY29tbWFuZC4KICAgICBUaGV5IG1heSBiZSBzdWZmaXhlZCBieSAiYm93IiBhbmQgdGhlbiBkaWN0YXRpb24gdG8gZm9ybWF0IChleDoKICAgICAidGllIHNuYWtlIGJvdyBzb21lIHdvcmRzIikgdG8gYWlkIHJlY29nbml0aW9uLgoKICAgLi4gcnVicmljOjogLiBGb3JtYXQgU2V0dGluZwogICAgICA6bmFtZTogZm9ybWF0LXNldHRpbmcKCiAgIHwgIAogICB8IHNldCBbYmlnXSBmb3JtYXQgPGNhcGl0YWxpc2F0aW9uPiA8c3BhY2luZz4gW2Jvd10gIAoKICAgLi4gY29udGFpbmVyOjogYWRkbWFyZ2luCgogICAgICAwZW0KCiAgICAgIC4uIGNvbnRhaW5lcjo6IGZsdXNocmlnaHQKCiAgICAgICAgIHwgKipTZXQgYSBzdGFuZGFyZC9bc2Vjb25kYXJ5XSBmb3JtYXQqKgogICAgICAgICB8ICAKCiAgIHwgW2JpZ10gZm9ybWF0IDxkaWN0YXRpb24+ICAqKkFwcGx5IHRoZSBzdGFuZGFyZC9bc2Vjb25kYXJ5XSBmb3JtYXQKICAgICB0byBkaWN0YXRpb24qKgoKICAgLi4gcnVicmljOjogLiBGcmVlIERpY3RhdGlvbiAtIEVuZ2luZSBGb3JtYXR0aW5nCiAgICAgIDpuYW1lOiBmcmVlLWRpY3RhdGlvbi0tLWVuZ2luZS1mb3JtYXR0aW5nCgogICB8ICAKICAgfCBzYXkgICoqZGVmYXVsdCBlbmdpbmUgZm9ybWF0dGluZyoqCiAgIHwgY29wICAqKkluaXRpYWwgbGV0dGVyIGNhcGl0YWxpemVkKioKICAgfCBzbGlwICAqKmluaXRpYWwgbGV0dGVyIGxvd2VyY2FzZSoqCgouLiBjb250YWluZXI6OiBwaWN0dXJlCgogICAoMjk3LDIxMCkgKDEwLDIwMCkKCiAgIC4uIHJ1YnJpYzo6IC4gUHJvZ3JhbW1pbmcgQ29yZQogICAgICA6bmFtZTogcHJvZ3JhbW1pbmctY29yZQoKICAgIAoKICAgfCBlbmFibGUgPGxhbmd1YWdlPiAgKiphY3RpdmF0ZSBtb2R1bGUqKgoKICAgLi4gY29udGFpbmVyOjogbXVsdGljb2xzCgogICAgICAyCgogICAgICB8IGlmZmFlCiAgICAgIHwgc2hlbGxzCiAgICAgIHwgc2hlbGwgaWZmYWUKICAgICAgfCBzd2l0Y2gKICAgICAgfCBicmVha2VyCiAgICAgIHwgZGVmYXVsdAogICAgICB8IGZvciBlYWNoCiAgICAgIHwgZm9yIGxvb3AKICAgICAgfCBkbyBsb29wCiAgICAgIHwgd2hpbGUgbG9vcAogICAgICB8IGNvbnZlcnQgdG8gaW50ZWdlcgogICAgICB8IGNvbnZlcnQgdG8gZmxvYXRpbmcgcG9pbnQKICAgICAgfCBjb252ZXJ0IHRvIHN0cmluZwogICAgICB8IGxvZGdlIGFuZAogICAgICB8IGxvZGdlIG9yCiAgICAgIHwgbG9kZ2Ugbm90CiAgICAgIHwgcHJpbnQgdG8gY29uc29sZQogICAgICB8IGZ1bmN0aW9uCiAgICAgIHwgY2xhc3MKICAgICAgfCBhZGQgY29tbWVudAogICAgICB8IGxvbmcgY29tbWVudAogICAgICB8IHZhbHVlIG5vdAogICAgICB8IHJldHVybgogICAgICB8IHZhbHVlIHRydWUKICAgICAgfCB2YWx1ZSBmYWxzZQoKICAgLi4gcnVicmljOjogLiBNaXNjZWxsYW5lb3VzIEhhcmR3YXJlIENvbnRyb2wKICAgICAgOm5hbWU6IG1pc2NlbGxhbmVvdXMtaGFyZHdhcmUtY29udHJvbAoKICAgIAoKICAgfCBtZWRpYSBbY29udHJvbF0gICoqcGxheXxwYXVzZSAvIG5leHR8YmFjayoqCiAgIHwgdm9sdW1lIDxtb2RlPiA8bj4gICoqdXB8ZG93biAvIG11dGV8dW5tdXRlKioKCiAgICgxMDUsMjAwKQoKICAgLi4gcnVicmljOjogLiBXaW5kb3cgTWFuYWdlbWVudAogICAgICA6bmFtZTogd2luZG93LW1hbmFnZW1lbnQKCiAgICAKCiAgIHwgbWluaW1pc2Ugd2luICAqKm1pbmltaXNlIHdpbmRvdyoqCiAgIHwgbWF4aW1pc2Ugd2luICAqKm1heGltaXNlIHdpbmRvdyoqCiAgIHwgZHJlZGdlICAgKiphbHQgKyB0YWIqKgogICB8IHN3aXRjaCB3aW5kb3cgICoqZGlzcGxheSBhbGwgd2luZG93cyoqCiAgIHwgbW92ZSB3aW5kb3cgICoqbW92ZSB3aXRoIGFycm93IGtleXMqKgogICB8IHdpbmRvdyBsZWZ0ICAqKnNuYXAgd2luZG93IHRvIGxlZnQqKgogICB8IHdpbmRvdyByaWdodCAgKipzbmFwIHdpbmRvdyB0byByaWdodCoqCiAgIHwgc2hvdyB3b3JrICAqKnNob3cgYWN0aXZlIHdvcmtzcGFjZXMqKgogICB8IG5ldyB3b3JrICAqKmNyZWF0ZSBhIG5ldyB3b3Jrc3BhY2UqKgogICB8IGNsb3NlIHdvcmsgICoqY2xvc2UgdGhlIGN1cnJlbnQgd29ya3NwYWNlKioKICAgfCBjbG9zZSBhbGwgd29yayAgKipjbG9zZSBhbGwgd29ya3NwYWNlcyoqCiAgIHwgcHJldmlvdXMgd29yayAgICoqZ28gdG8gdGhlIHByZXZpb3VzIHdvcmtzcGFjZSoqCiAgIHwgbmV4dCB3b3JrICAgKipnbyB0byB0aGUgbmV4dCB3b3Jrc3BhY2UqKgogICB8IGdvIHdvcmsgPG4+ICAqKmdvIHRvIHdvcmtzcGFjZSBudW1iZXIgbioqCiAgIHwgc2VuZCB3b3JrIDxuPiAgKipzZW5kIHRoZSBjdXJyZW50IHdpbmRvdyB0byB3b3Jrc3BhY2UgbioqCiAgIHwgbW92ZSB3b3JrIDxuPiAgKiptb3ZlIHRoZSBjdXJyZW50IHdpbmRvdyB0byB3b3Jrc3BhY2UgbioqCgogICAuLiBydWJyaWM6OiAuIFJlcGV0aXRpb24KICAgICAgOm5hbWU6IHJlcGV0aXRpb24KCiAgICAKCiAgIHwgYWdhaW4gZG8gICoqcmVwZWF0IGxhc3QgZGljdGF0aW9uKioKICAgfCBhZ2FpbiA8bj4gdGltZXMgICoqcmVwZWF0IGxhc3QgZGljdGF0aW9uKm4qKgogICB8IHJlY29yZCBmcm9tIGhpc3RvcnkgICoqb3BlbiBtYWNybyByZWNvcmRlcioqCiAgIHwgY29tcGxldGUgICoqc2F2ZSBtYWNybyoqCiAgIHwgZGVsZXRlIHJlY29yZGVkIG1hY3JvcyAgKipkZWxldGUgcmVjb3JkZWQgbWFjcm9zKioKCiAgIC4uIHJ1YnJpYzo6IC4gQWxpYXNpbmcKICAgICAgOm5hbWU6IGFsaWFzaW5nCgogICAgCgogICB8IGFsaWFzIDxkaWN0PiAgKiphbGlhcyBoaWdobGlnaHRlZCB0ZXh0KioKICAgfCBjaGFpbiBhbGlhcyA8ZGljdD4gICoqYWxpYXMgYXMgQ0NSKioKCiAgICgyMDAsIDIwMCkKCiAgIC4uIHJ1YnJpYzo6IC4gVGVtcGxhdGUtYmFzZWQgTmF2aWdhdGlvbgogICAgICA6bmFtZTogdGVtcGxhdGUtYmFzZWQtbmF2aWdhdGlvbgoKICAgIAoKICAgfCBqdW1wIGluICAgKiptb3ZlIGN1cnNvciBpbnNpZGUgbmV4dCAoW3s8KioKICAgfCBqdW1wIG91dCAgICoqbW92ZSBjdXJzb3IgcGFzdCBuZXh0ICldfT4qKgogICB8IGp1bXAgYmFjayAgICoqbW92ZSBjdXJzb3IgaW5zaWRlIHByZXYgKV19PioqCiAgIHwgZmlsbCA8dGFyZ2V0PiAgICoqaGlnaGxpZ2h0IDx0YXJnZXQ+IGluIGxpbmUqKgoKICAgLi4gcnVicmljOjogLiBNb3VzZSBSZXBsYWNlbWVudAogICAgICA6bmFtZTogbW91c2UtcmVwbGFjZW1lbnQKCiAgICAKCiAgIHwga2ljayAgKipsZWZ0IGNsaWNrKioKICAgfCBraWNrIG1pZCAgKiptaWRkbGUgY2xpY2sqKgogICB8IHBzeWNoaWMgICoqcmlnaHQgY2xpY2sqKgogICB8IHNoaWZ0IHJpZ2h0IGNsaWNrICAqKnNoaWZ0IHJpZ2h0IGNsaWNrKioKICAgfCBzaGlmdCBjbGljayAgKipzaGlmdCBjbGljayoqCiAgIHwgc3F1YXQgICoqbGVmdCBidXR0b24gZG93bioqCiAgIHwgYmVuY2ggICoqbGVmdCBidXR0b24gdXAqKgogICB8IGxlYW4gICoqcmlnaHQgYnV0dG9uIGRvd24qKgogICB8IGhvaXN0ICAqKnJpZ2h0IGJ1dHRvbiB1cCoqCiAgIHwgY29saWMgICoqY29udHJvbCBsZWZ0IGNsaWNrKioKICAgfCBzY3JlZSAgICoqc2Nyb2xsIHdoZWVsKioKICAgfCBjdXJzZSAgKiptb3ZlIGN1cnNvciBieSBwaXhlbHMqKgogICB8IGRvdWdsYXMgICoqbW92ZSBjdXJzb3Igb24gZ3JpZCoqCiAgIHwgcmFpbmJvdyAgKiphbHRlcm5hdGUgZ3JpZCoqCiAgIHwgbGVnaW9uICAqKnNtYXJ0IHRleHQgc2VsZWN0aW9uKioKICAgfCBsZWZ0IHBvaW50ICAqKm1vdXNlIHRvIHNjcmVlbiBsZWZ0KioKICAgfCBjZW50ZXIgcG9pbnQgICoqbW91c2UgdG8gc2NyZWVuIGNlbnRlcioqCiAgIHwgcmlnaHQgcG9pbnQgICoqbW91c2UgdG8gc2NyZWVuIHJpZ2h0KioKCiAgIC4uIHJ1YnJpYzo6IC4gRHJhZ29uCiAgICAgIDpuYW1lOiBkcmFnb24KCiAgICAKCiAgIHwgbnVtYmVyL3NwZWxsL2RpY3RhdGlvbi9ub3JtYWwvY29tbWFuZCBtb2RlICAqKnN3aXRjaCBkcmFnb24gbW9kZXMqKgoKICAgLi4gcnVicmljOjogLiBVcGRhdGUgYW5kIENhc3RlciBNYW5hZ2VtZW50CiAgICAgIDpuYW1lOiB1cGRhdGUtYW5kLWNhc3Rlci1tYW5hZ2VtZW50CgogICAgCgogICB8IGNhc3RlciA8bW9kZT4gICAqKm1pY3JvcGhvbmUgb24sIG9mZiwgc2xlZXAqKgogICB8IGNsZWFyIGNhc3RlciBsb2cgICoqQ2xlYXJzIExvZyBXaW5kb3cqKgogICB8IHVwZGF0ZSBkcmFnb25mbHkgICoqVXBkYXRlcyBEcmFnb25mbHkqKgogICB8IHJlYm9vdCBjYXN0ZXIgICoqUmVzdGFydHMgQ2FzdGVyKioKICAgfCBjYXN0ZXIgc2V0dGluZ3MgZWRpdG9yICAqKkNhc3RlciBzZXR0aW5ncyBlZGl0b3IqKgoKLi4gY29udGFpbmVyOjogcGljdHVyZQoKICAgKDI5NywyMTApICgxMCwyMDApCgogICAuLiBydWJyaWM6OiAuIEV4YW1wbGUgY29tbWFuZCBjaGFpbnMKICAgICAgOm5hbWU6IGV4YW1wbGUtY29tbWFuZC1jaGFpbnMKCiAgICAKCiAgIHNoYWNrbGUgY2xlYXIgIAoKICAgLi4gY29udGFpbmVyOjogYWRkbWFyZ2luCgogICAgICAwZW0KCiAgICAgIC4uIGNvbnRhaW5lcjo6IGZsdXNocmlnaHQKCiAgICAgICAgIHwgKipTZWxlY3QgYW5kIGRlbGV0ZSB0aGUgY3VycmVudCBsaW5lKioKICAgICAgICAgfCAgCgogICBxdWV1ZSBsZWFzZSBzdG9vc2ggdGhyZWUgIAoKICAgLi4gY29udGFpbmVyOjogYWRkbWFyZ2luCgogICAgICAwZW0KCiAgICAgIC4uIGNvbnRhaW5lcjo6IGZsdXNocmlnaHQKCiAgICAgICAgIHwgKipTdG9yZSB0aGUgcHJldmlvdXMgd29yZC92YXJpYWJsZSBuYW1lIGluIHBvc2l0aW9uIHRocmVlKioKICAgICAgICAgfCAgCgogICBxdWV1ZSBsZWFzZSB0aHJlZSBodWcgYnJheCAgCgogICAuLiBjb250YWluZXI6OiBhZGRtYXJnaW4KCiAgICAgIDBlbQoKICAgICAgLi4gY29udGFpbmVyOjogZmx1c2hyaWdodAoKICAgICAgICAgfCAqKkVuY2xvc2UgdGhlIHByZXZpb3VzIHRocmVlIGVsZW1lbnRzIGluIHNxdWFyZSBicmFja2V0cyoqCiAgICAgICAgIHwgIAoKICAgc2hhY2tsZSBjdXQgZHVuY2UgZm91ciBzcGFyayAgCgogICAuLiBjb250YWluZXI6OiBhZGRtYXJnaW4KCiAgICAgIDBlbQoKICAgICAgLi4gY29udGFpbmVyOjogZmx1c2hyaWdodAoKICAgICAgICAgfCAqKkN1dCB0aGUgY3VycmVudCBsaW5lLCBtb3ZlIGRvd24gZm91ciwgcGFzdGUqKgogICAgICAgICB8ICAKCiAgIHNoaW4gcm9zcyB3YWxseSBjbGVhciAgCgogICAuLiBjb250YWluZXI6OiBhZGRtYXJnaW4KCiAgICAgIDBlbQoKICAgICAgLi4gY29udGFpbmVyOjogZmx1c2hyaWdodAoKICAgICAgICAgfCAqKlNlbGVjdCB0byB0aGUgZW5kIG9mIHRoZSBsaW5lLCBkZWxldGUqKgogICAgICAgICB8ICAKCiAgIHJvc3Mgd2FsbHkgY2xlYXIgZm91ciAgCgogICAuLiBjb250YWluZXI6OiBhZGRtYXJnaW4KCiAgICAgIDBlbQoKICAgICAgLi4gY29udGFpbmVyOjogZmx1c2hyaWdodAoKICAgICAgICAgfCAqKkdvIHRvIHRoZSBlbmQgb2YgdGhlIGxpbmUsIGJhY2tzcGFjZSBmb3VyKioKICAgICAgICAgfCAgCgogICBzbmFrZSB2YXJpYWJsZSBuYW1lICAKCiAgIC4uIGNvbnRhaW5lcjo6IGFkZG1hcmdpbgoKICAgICAgMGVtCgogICAgICAuLiBjb250YWluZXI6OiBmbHVzaHJpZ2h0CgogICAgICAgICB8ICoqdmFyaWFibGVfbmFtZSoqCiAgICAgICAgIHwgIAoKICAgY3VybHkgcXVvdGVzIGFyY2ggcm9zcyBkZWNrbGUgcXVvdGVzIGJyb3YgIAoKICAgLi4gY29udGFpbmVyOjogYWRkbWFyZ2luCgogICAgICAwZW0KCiAgICAgIC4uIGNvbnRhaW5lcjo6IGZsdXNocmlnaHQKCiAgICAgICAgIHwgKip7ImEiOiJiIn0qKgogICAgICAgICB8ICAKCiAgIGJhY2tzbGFzaCBmb3JtYXQgY29tbWFuZCBjdXJseSAgCgogICAuLiBjb250YWluZXI6OiBhZGRtYXJnaW4KCiAgICAgIDBlbQoKICAgICAgLi4gY29udGFpbmVyOjogZmx1c2hyaWdodAoKICAgICAgICAgfCAqKlxcY29tbWFuZHt9KioKICAgICAgICAgfCAgCgogICAocHl0aG9uKSB0ZWxsIHNpbmsgcHJpbnQgdG8gY29uc29sZSBzcGFyayB0aHJlZSAgCgogICAuLiBjb250YWluZXI6OiBhZGRtYXJnaW4KCiAgICAgIDBlbQoKICAgICAgLi4gY29udGFpbmVyOjogZmx1c2hyaWdodAoKICAgICAgICAgfCAqKm5ldyBsaW5lLCBwcmludCg8dGhpcmQgY2xpcGJvYXJkIHBvc2l0aW9uPikqKgogICAgICAgICB8ICAK
)

It'll be a couple days before I can take a more in depth look as I'm finishing up some night shifts.

**Comment by und3fined-v01d** [comment]
@LexiconCode agreed the formatting seems clearly off from the expected. Please take your time to review this. Let me know if you have any pointers on how the formatting can be fixed.

**Comment by und3fined-v01d** [comment]
Hey @LexiconCode just curious if you got a chance to look at the PR?

**Comment by LexiconCode** [comment]
> 
> 
> Hey @LexiconCode just curious if you got a chance to look at the PR?

I have an after spending quite a bit of time trying to fight restructured text to get columns right. In part this is due to crappy editors for fight restructured text. I thought of a different approach that I mentioned an issue that this PR references. Basically using Microsoft Word/LibreOffice to create a word document with the appropriate columns and footings. This will be much easier to use and maintain over the long term. We can easily convert those files to PDFs and I also included an issue a method to allow git to diff for documents.

**Comment by LexiconCode** [comment]
> 
> 
> Hey @LexiconCode just curious if you got a chance to look at the PR?

Sorry for the delay I will be taking the next couple of days to try to hammer out one way or the other how to help you through this.

**Comment by und3fined-v01d** [comment]
@LexiconCode no worries please take your time 🙂...gives me enough time to understand the docs

**Comment by LexiconCode** [comment]
using the following editor
https://awesomeopensource.com/project/retext-project/retext
after install simply type in command prompt `ReText` to launch

```Text
##  Caster Quick Reference
| **1.** **Numbers**|                  | **5** **Directions**| **9.** **Text Formatting**|
|-------------------|------------------|---------------------|---------------------------|
|numb <0..1m>       |**print digits**  |sauce   **up**       |                           |
|word number <0...9>|**print as words**|dunce   **down**     |                           |
|                   |                  |ross    **right**    |                           |
|                   |                  |lease   **left**     |                           |
|                   |                  |                     |                           |
|                   |                  |                     |                           |
|                   |                  |                     |                           |
|                   |                  |                     |                           |
|                   |                  |                     |                           |
|                   |                  |                     |                           |
```
Renders as
image

I'm short on time but this looks like a place to get started. We can continue to add more fancy formatting as we go along which I can help with as time allows.

**Comment by LexiconCode** [comment]
@ und3fined-v01d here's an example. 1st an editor. [retext](url) is simple but Is only one I could find it's reasonably up-to-date. `pip install ReText` and launch the command line using `ReText`.

An example document

```
Caster Quick Reference
======================

+----------------------------------+
|\1. Numbers                       |
+==================================+
|numb <0...1m> print digits [e]_   |
+----------------------------------+
|word number <0...9> print as words|
+----------------------------------+

+-------------------------+
|\2. Alphabet             |
+=========================+
|arch brov char delta echo|
+-------------------------+
|foxy goof hotel india    |
+-------------------------+
|julia kilo lima mike     |
+-------------------------+
|novakeen oscar prime     |
+-------------------------+
|quebec romeo sierra      |
+-------------------------+
|tango uniform victor     |
+-------------------------+
|whiskey x-ray yankee zulu|
+-------------------------+

.. [e] Prefix 'long' to get spaces on either side.
```

An awesome [rst cheatsheet](https://github.com/ralsina/rst-cheatsheet/blob/master/rst-cheatsheet.rst) which has a lot of cool examples with how they render. So that should give us the flexibility we need. This should set you up for success working through the Caster Quick Reference.

**Comment by und3fined-v01d** [comment]
@LexiconCode thank you so much for the example. Planning to sit through and work out the remaining doc this weekend. I'll update this PR accordingly

**Pull request closed without merging**
