### PR TITLE
add Talon alphabet but leave it commented out

### PR DESCRIPTION
**Pull request by alexboche**

### CODE REVIEW

**Comment by kendonB** [comment]
Should this sort of thing really be included via `words.txt`?

**Comment by LexiconCode** [comment]
I would be hesitant to add it to the main repository because of permissions and commented code as a source of customization is undesirable. However it does not mean I don't think it's useful or that it should not be preserved. 

An alternative would be to document caster user setups. Therefore reducing fragmentation of how Caster users implement customizations.  Caster users could include `.caster` and upload it to a separate repository or branch. We could then link it in the Caster Documentation to show off user customizations and implementations.

**Comment by kendonB** [comment]
One day I'd like for everyone to be able to to all customizations using just the `.caster` folder and not touching, nor ever wanting to touch, the main source. @alexboche would you like to convert this content to a mock `words.txt` and then link a gist here?

**Comment by alexboche** [comment]
I haven't really use words.txt. would it be like this?
arch -> air
brov -> bat

**Comment by kendonB** [comment]
Mine is here and it includes a few alphabet changes:
https://github.com/kendonB/dot_caster/blob/master/data/words.txt

**Pull request closed without merging**
