### PR TITLE
Revert clipboard to use json

### LINKED ISSUE #357: Bugs in handling non-ASCII characters in clipboard over restarts
1. If I select "závorka", do "stoosh three", restart Dragon and do "spark three", I get `zxe1vorka`. It should be encoded as `z\xe1vorka`. Probably affects characters 128-255. Confirmed by @mrob95 

2. Certain saved clipboard items give
```
<class 'toml.decoder.TomlDecodeError'>
Reserved escape sequence used (line 1 column 1 char 0)
<traceback object at 0x0EF9EB48>
  File "C:\workspaces\dns_userdir\caster\lib\utilities.py", line 85, in load_toml_file
    result = toml.loads(f.read())

  File "C:\Python27\lib\site-packages\toml\decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
```

A clipboard file is pasted here: https://pastebin.com/jGeV5jvE

### PR DESCRIPTION
**Pull request by comodoro**
Finally resolve #357 the least inventive way. Reasons in the issue, unable to fix toml. By the way if more exotic languages where Unicode is needed for dictation are supported, this will become an issue again with aliases, macros etc.

### CODE REVIEW

**Comment by kendonB** [comment]
#485 still works after this change, FYI

**Comment by kendonB** [comment]
Saw this error just now:
```
<type 'exceptions.ValueError'>
Extra data: line 1 column 4 - line 4 column 1 (char 3 - 56)
<traceback object at 0x12E19FA8>
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\utilities.py", line 137, in load_json_file
    result = json.load(json_file)

  File "C:\Python27\Lib\json\__init__.py", line 291, in load
    **kw)

  File "C:\Python27\Lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)

  File "C:\Python27\Lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
```

**Comment by comodoro** [comment]
@kendonB Could you please specify more closely when does the error occur and contents of `clipboard.json`?

**Comment by kendonB** [comment]
I see it upon startup and I don't see `clipboard.json` in there at all. Only toml. Do you need to send it to `.caster` if it's not already there?

**Comment by comodoro** [comment]
Oh, (facepalm), I forgot that everyone will still have clipboard.toml in their settings.toml. If you change `SAVED_CLIPBOARD_PATH` to clipboard.json, it should work.

**Comment by kendonB** [comment]
Shouldn't the PR try to do that itself?

**Comment by comodoro** [comment]
It does with settings.py, however it cannot touch your already generated user settings. It would be possible to create new constant in settings.py for this, but the old one would still hang in users' files, so I did not (it is the same as with moving to toml before)

**Comment by comodoro** [comment]
Although after some thought I can see its merit in reducing users' disturbance. What do you think?

**Comment by kendonB** [comment]
I think it's fine to change the path in `settings.toml` via `settings.py` if it's `USER_DIR + "data/clipboard.toml"`

**Comment by comodoro** [comment]
@kendonB Do you mean like adding this specific check (probably in the `_init` function)? It looks a bit suspicious, but with clear indication that it is temporary I have no problem with that.

**Comment by kendonB** [comment]
I was thinking it would be in `settings.py`? Because that already writes new settings elements into `settings.toml` and this would just instead write over an existing settings element.

**Comment by comodoro** [comment]
@kendonB Sorry for the delay. Is the migrate commit what you had in mind? It is ugly and duplicates I/O (because of impirting order; utilities have to be refactored), but I am hoping we will be able to remove it before merging into master.

**Comment by kendonB** [comment]
shouldn't it also remove the `clipboard.toml`?

**Comment by kendonB** [comment]
I am no longer seeing the error though

**Comment by comodoro** [comment]
@kendonB Sorry, yes, thanks, added. Note though that if you already have the path changed from trying this PR, it will not be touched.

**Comment by kendonB** [comment]
I updated this PR locally, changed my clipboard path back to the toml in settings, and now see the old clipboard file disappear. Great! I'm going to merge this.

**Comment by LexiconCode** [comment]
This error keeps popping back up. Looks like it's trying to read clipboard.json as Toml file.
@comodoro 
```
<class 'toml.decoder.TomlDecodeError'>
Found invalid character in key name: '}'. Try quoting the key name. (line 1 column 2 char 1)
<traceback object at 0x1C43C170>
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\utilities.py", line 113, in load_toml_file
    result = toml.loads(f.read())

  File "C:\Python27\lib\site-packages\toml\decoder.py", line 227, in loads
    original, i)


```

**Comment by comodoro** [comment]
@LexiconCode Can happen now if developers switch branches with and without this (and the opposite, if you remake toml clipboard on an old branch). I think for users it should be safe.

**Comment by LexiconCode** [comment]
That makes total sense.

**Comment by LexiconCode** [comment]
@comodoro should we keep using json for clipboard?
Then remove the following temporary code for migrating https://github.com/dictation-toolbox/Caster/blob/5aecbf0ff7c292bf31af7fe9f21390db588f2fcd/castervoice/lib/settings.py#L440

**Pull request merged**
