### PR TITLE
[WIP] Fix for words.txt and filter rules

### PR DESCRIPTION
**Pull request by comodoro**
For #354, starting with the quick fix

### CODE REVIEW

**Comment by LexiconCode** [comment]
Do you consider this complete?

**Comment by comodoro** [comment]
I am not sure how is the replacement supposed to work, I commented on the underlying issue (#354), maybe I should comment here as well

**Comment by LexiconCode** [comment]
Experimenting with the word.txt global simplified filter rules with your pull request.

Testing **selfmodifying** rules
These have two seem to have no effect
```
<<<SPEC>>>
alias -> gumption
```
```
<<<NOT_SPECS>>>
alias -> gumption
```

Testing **MergeRule**
Does not work but it does not work in the development branch either
```
<<<NOT_SPECS>>>
nexta -> cat
```

Works as expected
```
<<<SPEC>>>
nexta -> cat
```
I'll have to look into it further but let me know what you think.

**Comment by comodoro** [comment]
@LexiconCode Thanks for pinging me. The pull request does not contain the modifications for the replacement logic yet, only fix for the exception mentioned in the issue. The alias command (and chain alias) are a bit special in that the specs are hardcoded and reset with init and each change. Besides there is that it is being loaded twice (_caster.py and alias.py), I am not sure where we landed on that.

So I think we are agreed on replacement of words(and phrases), but it might be worth considering also supporting whole specs (commands) besides that, like it is now.

**Comment by LexiconCode** [comment]
I apologize, thanks for clarifying. It might be worth considering utilizing toml instead of txt. In the future pull request we could add modifications by voice.

At this for replacing specs the logic is in place already in [scen4.py](https://github.com/synkarius/caster/blob/bc5b2b8bd4a2495c910a4beb4260d50847f922a9/caster/user/filters/examples/scen4.py#L34) I thought about making its own toml file for complete spec replacement. That was my thought but it's worth discussing which is a better approach.

**Comment by comodoro** [comment]
That is a good point, toml is readable, and makes things easier. A might be perceived disadvantage might be having to quote spaces and Unicode. Voice modifications seem possible.

Complete spec replacement is currently there
https://github.com/synkarius/caster/blob/bc5b2b8bd4a2495c910a4beb4260d50847f922a9/caster/lib/dfplus/merge/gfilter.py#L153-L156
I think easiest currently would be adding a new header for words and phrases and altering current extras replacement from substrings to words and phrases. The other things can be addressed in future.

**Comment by LexiconCode** [comment]
@comodoro are you okay with me closing this issue or should we keep it open?

**Comment by comodoro** [comment]
OK, This is too old, I will review the issue and possibly create a new one.

**Pull request closed without merging**
