### PR TITLE
Rule loading functions in control.py

### PR DESCRIPTION
**Pull request by mrob95**
As mentioned in #589  I have implemented a series of functions in `control.py` to simplify and standardise the API for adding rules.

The only question I have at the moment is about lines like:
```
if settings.SETTINGS["apps"]["firefox"]:
```

Which only load app rules if the relevant value is set to true in the settings. Is there a good reason why this is necessary? Does anybody need the ability to disable particular app rules (perhaps RDP users)? @LexiconCode

### CODE REVIEW

**Comment by LexiconCode** [comment]
I use RDP quite a bit in remote work. I've not really use disabling apps. Other people I know on the past have done that as they've had a preferred grammar that the choose to use over casters implementation.

Perhaps we can automate writing to app name toml using control.py. Perhaps it can pull from the grammar name and populate the entries without user intervention.

**Comment by seekM** [comment]
> Other people I know on the past have done that as they've had a preferred grammar that the choose to use over casters implementation.

When app rules are copied to user space in the future, the copies are used automatically, aren't they? Wouldn't this make this value irrelevant? (I haven't used RDP and can't speak for this)

**Comment by LexiconCode** [comment]
> > Other people I know on the past have done that as they've had a preferred grammar that the choose to use over casters implementation.
> 
> When app rules are copied to user space in the future, the copies are used automatically, aren't they? Wouldn't this make this value irrelevant? (I haven't used RDP and can't speak for this)

I think that is true and shouldn't have any impact on RDP.

**Comment by mrob95** [comment]
@seekM this is my instinct, I'm not sure I can think of a situation where somebody would really need to disable particular app grammar, that if they needed to they could just make a blank file in their user space with the same name, or if this got cumbersome then we can come up with a better way.

Having to add lines to the settings file for each app when the vast majority of users will just want to leave them all on all the time seems like a waste. Can we just drop it?

**Comment by LexiconCode** [comment]
> Can we just drop it?

let's drop it

**Comment by seekM** [comment]
> that if they needed to they could just make a blank file in their user space with the same name 

Maybe deleting them could also work? Don't know how copying rules to user folder is supposed to work exactly, but if everything is copied, only apps rules in the user folder could be considered for loading? Then simply having no file would work.

Personally I have some of them disabled even though I don't use custom ones for them just because it feels unclean to me to have them loaded if they will never be active. This probably isn't a good reason though, so I'm fine with dropping it to.

**Pull request merged**
