### PR TITLE
Redesign rdescripts

### PR DESCRIPTION
**Pull request by mrob95**
Currently, the accepted formatting for a caster command looks something like this:
```
"function": R(Text("def ():") + Key("left:2"), rdescript="Python: function"),
```

We have the verbal command, R - which creates a registered action, the actual dragonfly objects to be executed, and an rdescript written by whoever wrote the grammar to describe the command.

There are a number of problems with this construction.

1. It's long, often requiring multiple lines to define a single command.
2. It's verbose, only about half of the character count is actually useful code, the rest is verbiage.
3. It's a bug magnet, with a lot of potential for misplaced commas and brackets and misspelled words.
4. rdescripts are inconsistent between different authors and are a pain to write.

The combination of these problems end up making the code base harder to read and harder to work on, with little appreciable benefit.

The aim of this pull request is to radically simplify this construction, pushing stuff which should really be backend into the backend and out of the user's way. 

So far I have:
* Altered the execution of registered action so that dynamic elements can be added into the rdescript.
* Altered the merge rule so that all registered actions which do not have an rdescript will be given one, containing the name of the class, the command spec, and the extras to be dynamically added on execution.
* Deleted all rdescripts from the Python module for testing purposes.

A further improvement would be to have dragonfly objects be automatically converted to registered actions, removing the need for `R` as well. This should be possible but needs some work, as at the moment it causes a nasty dependency cycle.

Happy to get any thoughts.

### CODE REVIEW

**Comment by LexiconCode** [comment]
This is an excellent pull request as it addresses many of the points in dictation-toolbox/Caster#235. 

A number of issues so far.
1. Despite picking a different element choice the print out remains choice element first item for instance `Python: try [<exception>], StandardError`

2. The natlink window goes blank until switching non choice element or a different choice element from previous spoken.  For instance switching from "binary_meth" to "exception" (I've experienced this before but this seems to be exacerbated with this pull request)

3. `meth [<unary_meth>]`  only print out default which is an empty string.

> A further improvement would be to have dragonfly objects be automatically converted to registered actions, removing the need for `R` as well. This should be possible but needs some work, as at the moment it causes a nasty dependency cycle.

Personally pull request is already a large improvement. However I would get further feedback in Gitter from the community before implementing the above suggestion.

**Comment by LexiconCode** [comment]
Two following issues have been resolved.
> 1. meth [<unary_meth>] only print out default which is an empty string.
> 3.Despite picking a different element choice the print out remains choice element first item for instance Python: try [<exception>], StandardError
Clarify 2 is not a bug with the pull request.

4. With default Configdebug.txt removing rdescript from a command causes it to print out to `none`.  most likely due to how the unconventional way configdebug is loaded over the issue below. 

5. Specs that include `Repeat(extra="n")` print out to `None`

```Python
        "Unindent [<n>]":
            R(Key("s-tab")) * Repeat(extra="n"),
```

**Other notes**
Is there a way to handle repeat elements with a number instead of printing out x repetitions?
For instance say "Next Tab 3"

Printout 
```
Core: Next Tab
Core: Next Tab
Core: Next Tab
```

**Comment by mrob95** [comment]
> 1. With default Configdebug.txt removing rdescript from a command causes it to print out to `none`.  most likely due to how the unconventional way configdebug is loaded or related to the issue below.
This may be fixable, but is probably one for a different request since the mechanism would be quite different - currently this way only applies to merge rules when they are instantiated.

> 2. Specs that include `Repeat(extra="n")` without rdescript print out to `None`
> 
> ```python
>         "Unindent [<n>]":
>             R(Key("s-tab")) * Repeat(extra="n"),
> ```
Fixed. With the repeat outside of the R it was creating a dragonfly object instead of a registered action.

> 1. `make fake RegisteredAction` unit test may need to be reworked
Will check it out.


> **Other notes**
> Is there a way to handle repeat elements with a number instead of printing out x repetitions?
> For instance say "Next Tab 3"
> 
> Printout
> 
> ```
> Core: Next Tab
> Core: Next Tab
> Core: Next Tab
> ```
> is it possible to get at Dictation elements?
These should all work now.

**Comment by LexiconCode** [comment]
With the Markdown CCR the element choice is not included.
```
Markdown: insert <element>, backtick:2, left
Markdown: insert <element>, asterisk:4, left:2
Markdown: insert <element>, dollar, dollar, left
```

**Comment by mrob95** [comment]
At the moment that markdown behaviour is as expected - it will print the relevant value from the Choice dict.

rdescripts are only generated for Mergerules, the navigationnon was a mapping rule which was why it wasn't working. Fixed.

For reference, this is the query I'm using to delete rdescripts.

```
,\s?+rdescript=\".*?\"
```

**Comment by LexiconCode** [comment]
So far I haven't had any more issues during testing. I believe we can be pretty liberal about removing most rdescript with the exception of those that are functionally descriptive beyond the command name. an example of this might be 
```
        "garb [<nnavi500>]":
            R(Mouse("left") + Mouse("left") + Function(
                navigation.stoosh_keep_clipboard,
                nexus=_NEXUS),
              rdescript="Core: Highlight @ Mouse + Copy"), 
```

**Comment by kendonB** [comment]
Is it still possible to have this? https://github.com/dictation-toolbox/Caster/issues/234

**Comment by seekM** [comment]
@LexiconCode As you said you haven't experienced more issues, can this be merged? 
In this PR `NavigationNon` is changed from a `MappingRule` to a `MergeRule`. In general all rules listed as a `non` should be changed from `MappingRule` to a `MergeRule`, shouldn't they @mrob95? What else has to be done? I'm looking forward to this because it would solve the issue I have that I can't change specs in  `MappingRule`s like `NavigationNon` without touching non user Caster files (see #466).

**Comment by mrob95** [comment]
Going to merge this before there are too many more merge conflicts. Removing rdescripts can be done gradually. I'm busy with exams at the moment but can make time if there are any bugs with this that need fixing.

**Comment by kendonB** [comment]
@mrob95 Can you summarise here what the new best practice is for rdescripts? And potentially pin the issue?

**Comment by mrob95** [comment]
@kendonB Unless there is a particularly good reason I think best practice would be to not include rdescripts, and I think we should be aiming to remove them from the code base over time.

**Comment by kendonB** [comment]
Can you give an example of "a particularly good reason"? If the spec was very opaque about what was trying to do?

**Comment by LexiconCode** [comment]
> 
> 
> Can you give an example of "a particularly good reason"? If the spec was very opaque about what was trying to do?

That's pretty much it as seen in my example above. Where the command name is not descriptive enough to describe its function.

**Pull request merged**
