### PR TITLE
Implements tomlkit in place of toml dependency

### PR DESCRIPTION
**Pull request by LexiconCode**
A work in progress is not ready for testing.

Fixes  non-ASCII characters in clipboard
https://github.com/dictation-toolbox/caster/issues/357 

Implements sorting keys
https://github.com/dictation-toolbox/caster/issues/323

### CODE REVIEW

**Comment by LexiconCode** [comment]
raceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 12, in <module>
    from caster.lib.ccr.standard import SymbolSpecs
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\ccr\__init__.py", line 3, in <module>
    from caster.lib import utilities
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\utilities.py", line 27, in <module>
    from caster.lib import settings
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\settings.py", line 140, in <module>
    "ENGINE_PATH": _validate_engine_path(),
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\settings.py", line 47, in _validate_engine_path
    data = parser(toml_file.read())
TypeError: 'module' object is not callable

**Comment by comodoro** [comment]
`from tomlkit import dumps, parse`, not `parser`, according to docs. Sorry I have no time to try it, going to hospital Monday.

**Comment by LexiconCode** [comment]
Oh my goodness. Not a problem.   Yep that's probably the issue small typo on my part.

**Comment by LexiconCode** [comment]
```Python
Error loading _caster from "C:\NatLink\NatLink\MacroSystem\_caster.py"
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 168, in <module>
    _NEXUS.merger.merge(MergeInf.BOOT)
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\dfplus\merge\ccrmerger.py", line 352, in merge
    self._add_grammar(base, True, negation_context)
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\dfplus\merge\ccrmerger.py", line 215, in _add_grammar
    repeater = self._create_repeat_rule(rule)
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\dfplus\merge\ccrmerger.py", line 402, in _create_repeat_rule
    sequence = Repetition(single_action, min=1, max=max, name=SEQ)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\elements_basic.py", line 555, in __init__
    assert max is None or isinstance(max, int)
AssertionError
```
So a bit of debugging on this aspect. it appears that there's differences between tomlkit integers and pythons. 

"caster\lib\dfplus\merge\ccrmerger.py", line 401
max = settings.SETTINGS["miscellaneous"]["max_ccr_repetitions"]
print type(max)# <class 'tomlkit.items.Integer'> vs expected <type 'int'>

Temporary Fix
max = int(settings.SETTINGS["miscellaneous"]["max_ccr_repetitions"])

Which leads to
```Python
Error loading _caster from "C:\NatLink\NatLink\MacroSystem\_caster.py"
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\NatLink\NatLink\MacroSystem\_caster.py", line 168, in <module>
    _NEXUS.merger.merge(MergeInf.BOOT)
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\dfplus\merge\ccrmerger.py", line 376, in merge
    self._apply_format(current_rule)
  File "C:\NatLink\NatLink\MacroSystem\caster\lib\dfplus\merge\ccrmerger.py", line 241, in _apply_format
    if name in settings.SETTINGS["formats"]:
  File "C:\Python27\lib\site-packages\tomlkit\container.py", line 494, in __contains__
    key = Key(key)
  File "C:\Python27\lib\site-packages\tomlkit\items.py", line 187, in __init__
    [c not in string.ascii_letters + string.digits + "-" + "_" for c in k]
TypeError: 'NoneType' object is not iterable
```

**Comment by LexiconCode** [comment]
It appears that tomlkit has special types for (String, Integer, Float, Bool, etc.) hence the differences between <class 'tomlkit.items.Integer'> vs expected <type 'int'>. unlike the previous toml Implementation.

That being said I think that tomlkit maybe only for editing and creating toml documentation not
in code. Although it was like a second opinion from anyone that has time.

**Comment by comodoro** [comment]
@LexiconCode Where did you get that exception? I am trying to just change the import and have not noticed any problems yet. Could you please, eventually, try version 0.5.5?

**Comment by comodoro** [comment]
(I am revisiting this because I am realizing English also suffers from incorrect toml saving, albeit just slightly, with loanwords)

**Comment by LexiconCode** [comment]
That's great news, I'll look into it soon.

**Comment by LexiconCode** [comment]
> 
> 
> (I am revisiting this because I am realizing English also suffers from incorrect toml saving, albeit just slightly, with loanwords)

I'll be looking into this issue next!

**Comment by LexiconCode** [comment]
> 
> 
> @LexiconCode Where did you get that exception? I am trying to just change the import and have not noticed any problems yet. Could you please, eventually, try version 0.5.5?

I've created a [branch](https://github.com/LexiconCode/Caster/tree/tomlkit) with the changes. The following error happens during startup.

```
Caster User Directory: C:\Users\Laptop\.caster
Caster: dragonfly is up-to-date
Error loading _caster from C:\Users\Laptop\Documents\Caster\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\Laptop\Documents\Caster\_caster.py", line 49, in <module>
    _NEXUS.merger.merge(MergeInf.BOOT)
  File "C:\Users\Laptop\Documents\Caster\castervoice\lib\dfplus\merge\ccrmerger.py", line 371, in merge
    self._add_grammar(base, True, negation_context)
  File "C:\Users\Laptop\Documents\Caster\castervoice\lib\dfplus\merge\ccrmerger.py", line 223, in _add_grammar
    repeater = self._create_repeat_rule(rule)
  File "C:\Users\Laptop\Documents\Caster\castervoice\lib\dfplus\merge\ccrmerger.py", line 425, in _create_repeat_rule
    sequence = Repetition(single_action, min=1, max=max, name=SEQ)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\elements_basic.py", line 564, in __init__
    assert max is None or isinstance(max, int)
AssertionError
```

**Comment by LexiconCode** [comment]
> So a bit of debugging on this aspect. It appears that there's differences between tomlkit api and json/toml read keys.
> 
> "caster\lib\dfplus\merge\ccrmerger.py", line 401
> `max = settings.SETTINGS["miscellaneous"]["max_ccr_repetitions"]`
> `print type(max)`# <class 'tomlkit.items.Integer'> vs expected <type 'int'>

Function to convert everything to plain old python objects 
https://github.com/sdispater/tomlkit/issues/43

**Comment by LexiconCode** [comment]
@comodoro With tomlkit if directory is deleted then caster loads fine the first time.  the 2nd load the assertion error appears.

**Comment by comodoro** [comment]
Oops, I had not actually changed it in settings, sorry. Your link actually solves it - the `value` property, Dragonfly is a bit overzealous in type checking in this case, but the remedy is quite straightforward

**Comment by comodoro** [comment]
https://github.com/dictation-toolbox/dragonfly/pull/125 (`value` uses long)

**Comment by LexiconCode** [comment]
@comodoro can you give an example of how the value method would be used in loading toml?

**Comment by comodoro** [comment]
Just using it on the loaded dictionary:

```
data = tomlkit.loads(toml_file.read()).value
```
Only right now Dragonfly expects int where tomlkit returns long (the exception above). I hope there are no more problems, at least I have not encountered any.

**Comment by LexiconCode** [comment]
> 
> 
> Just using it on the loaded dictionary:
> 
> ```
> data = tomlkit.loads(toml_file.read()).value
> ```
> 
> Only right now Dragonfly expects int where tomlkit returns long (the exception above). I hope there are no more problems, at least I have not encountered any.

Alright thanks for that! Indeed does work. I will make a new pull request!

**Pull request closed without merging**
