### PR TITLE
Voice dev commands tweak

### PR DESCRIPTION
**Pull request by alexboche**
Remove unwanted comma.

### CODE REVIEW

**Comment by alexboche** [comment]
Currently the command for the rdescript prints out `rdescript="MyGrammar: "` . Lexicon code said that the rdescripts are no longer as important. Should we change the command so that it just prints out `rdescript=""),` ?

**Comment by kendonB** [comment]
I would just remove the first space but keep it. 
```
"dev descript":
    R(Text(' rdescript="MyGrammar: "') + Key("left"), rdescript="CasterDev: Add the rdescript")
```
you could also fix up the problem in #531

**Comment by kendonB** [comment]
you might also want to add an optional "with r descript" to the command phrases for when users want to add rdescripts

**Comment by kendonB** [comment]
lots of these functions also expect the editor to auto complete parentheses and curly braces. the default should be that they work without needing to use an editor's autocomplete

**Pull request merged**
