### PR TITLE
Prevent multiple navigation overlays from stacking

### PR DESCRIPTION
**Pull request by BenChand**
# Title

Prevent multiple navigation overlays from stacking

## Description

Currently it's possible to trigger multiple navigation modes at once, causing grids like rainbow and sudoku to overlap with one another. This becomes confusing because it's not obvious what order is needed to exit these grids.

This change also check to see if any other navigation mode has been started, and if so, raises an exception so that the new navigation mode doesn't wait around for its window to appear.

## Motivation and Context

I keep triggering multiple ones by accident and wanted to fix it.

## How Has This Been Tested

Manual testing, tracking that new navigation modes can not be triggered if one is currently on the screen

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue or bug)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Renamed existing command phrases (we discourage this without a strong rationale).

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] I have checked for and utilized existing command phrases from within Caster (delete if not applicable). 
- [x] My code implements all the features I wish to merge in this pull request.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests pass.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

### CODE REVIEW

**Comment by BenChand** [comment]
Not sure why the python2 build is failing, can't see it being related to the changes

**Comment by LexiconCode** [comment]
Are you on the latest master? That should be fixed. The Microsoft c++ compilers are no longer available for Python 2.7. Therefore a package can't compile. It was resolved by including a pre-compiled package for regex.

Fortunately when we drop Python 2 support this will no longer be an issue.

**Comment by BenChand** [comment]
Yeah this is using the latest on master I believe

**Comment by LexiconCode** [comment]
This issue will be fixed in the next release of dragonfly.

**Pull request merged**
