### PR TITLE
Convert bringme feature to non ccr

### PR DESCRIPTION
**Pull request by kendonB**
# Change bringme to not be CCR

## Description

I took the approach in `simple_alias.py` and simply ported it over to `bringme.py`.

## Motivation and Context

Bring me should not be CCR - my main problem I was having was that I was getting complexity errors due to having so many bringme items.

## How Has This Been Tested
I made the changes, rebooted caster, and just made sure that bring me still worked as well as it now not giving complexity errors when enabled along with other languages.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue or bug)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Renamed existing command phrases (we discourage this without a strong rationale).

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] My code implements all the features I wish to merge in this pull request.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

P.S. I actually don't know how to run unit tests any more. We should add the command for that to the contributing document.

### CODE REVIEW

**Comment by LexiconCode** [comment]
I will test this on tomorrow after I get some sleep. We should double check making sure we can add and remove keys by voice.

**Comment by LexiconCode** [comment]
Testing results
- Successful adding new key website/program
- No longer CCR
- Failure to remove bring me \<key> despite command being recognized. 
	Not related to this PR. Can you replicate?
- `Refresh bring me` works when manually editing keys.
-  syntax errors\key duplicates restore default bring me file.
	Unrelated to this pull request worth testing

**Comment by alexboche** [comment]
All else being equal, ccr is better (though can also lead to misrecognitions or perhaps slower processing speed?) I believe it is possible to eliminate the grammar complexity issue. In Talon, all commands are ccr and the problem of complexity does not arise as far as I know. I wouldn't be surprised if @daanzu has the knowledge (though not necessarily the time) to get rid of the grammar complexity problem since it might have to do with compilers which he is knowledgeable on.

**Comment by kendonB** [comment]
@LexiconCode I can replicate the issue where remove from bring me doesn't work.

**Comment by kendonB** [comment]
@LexiconCode do you remember who lifted the last big overhaul of bring me? Was it @mrob95 ?

**Comment by kendonB** [comment]
@LexiconCode would you want these additional issues addressed in this PR? It is not immediately obvious to me how to fix them.

**Comment by LexiconCode** [comment]
> 
> 
> @LexiconCode would you want these additional issues addressed in this PR? It is not immediately obvious to me how to fix them.

I'll look into it first and reach out if I can't previous contributors.


> All else being equal, ccr is better (though can also lead to misrecognitions or perhaps slower processing speed?) I believe it is possible to eliminate the grammar complexity issue. In Talon, all commands are ccr and the problem of complexity does not arise as far as I know. I wouldn't be surprised if @daanzu has the knowledge (though not necessarily the time) to get rid of the grammar complexity problem since it might have to do with compilers which he is knowledgeable on.

Yes until CCR is implemented directly within Dragon by itself this will be unlikely to be optimized. Creating that implementation is not on the radar at this time for current maintainers). CCR this is more of a Caster thing that builds off the repetition rule in Dragonfly. F

**Pull request merged**
