### PR TITLE
Document Kaldi installation on MacOS

### PR DESCRIPTION
**Pull request by Timoses**
# Document Kaldi installation on MacOS

## Description

No installation instructions for MacOS using Kaldi are supported in the documentation. This should give a first basis as a reference for future documentation improvements. It was inspired by https://github.com/kmdouglass/homelab/blob/master/speech-recognition/toolchains/caster-kaldi/Dockerfile .

## Related Issue

--

## Motivation and Context

Document installation steps required to install Caster with Kaldi on MacOS.

## How Has This Been Tested

Tested with `mkdocs`.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] I have updated the documentation accordingly.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

### CODE REVIEW

**Comment by LexiconCode** [comment]
I appreciate the support! I have been working on install [instructions](https://caster-lexiconcode.readthedocs.io/en/docs/readthedocs/Installation/MacOS/Kaldi_MacOS/). Let me know what you think!

I haven't opened up a PR yet as I'm still testing with Linux and working on getting BringMe cross-platform.

**Comment by Timoses** [comment]
It looks good. Though, I am not able to find the referenced shell scripts `Install_Caster_Kaldi.sh` and `Run_Caster_Kaldi.sh`.

Feel free to close this PR. I'm sure you have something along those lines in the (not yet committed?) shell scripts.

**Comment by LexiconCode** [comment]
> (not yet committed?)

It's a bit frustrating with shell scripts. It seems not only do they need permissions but clicking on them does not always execute depending on the system especially with Linux.

**Comment by Timoses** [comment]
At least git commits file modes.

I suppose until Caster is nicely wrapped in some kind of service application the shell may at times be neccessary.

I'm closing this PR as it can still be used as a reference to update or improve other improvement efforts on documentation.

**Pull request closed without merging**
