### PR TITLE
change comment from cancel to terminate

### PR DESCRIPTION
**Pull request by kendonB**
I'm not sure if the "cancel" in quotes should also be changed/removed

### CODE REVIEW

**Comment by Versatilus** [comment]
I'll check that out after dinner.

**Comment by Versatilus** [comment]
Technically, it runs until `SymbolSpecs.CANCEL` is said.  I'm still not sure if "cancel" should be removed. There's a lot of code here to unwind. I'll keep on staring at it tonight.

**Comment by LexiconCode** [comment]
I'm not exactly sure why we would change it from "cancel" to "terminate". I would think the average person would think of "cancel" before "terminate" to stop an action.

**Comment by Versatilus** [comment]
> I'm not exactly sure why we would change it from "cancel" to "terminate". I would think the average person would think of "cancel" before "terminate" to stop an action.

Unintuitively, "cancel" doesn't cause the action because the word isn't part of the spec defined by `SymbolSpecs.CANCEL`. Now that you have pointed this out it makes me think the right change is to change the spoken words  to include "cancel".

**Comment by kendonB** [comment]
Ref #153

**Comment by LexiconCode** [comment]
> 
> 
> Ref #153
I'll do some testing but I think dragonfly or natlink now overrides built-in Dragon commands.

**Comment by Versatilus** [comment]
> I'll do some testing but I think dragonfly or natlink now overrides built-in Dragon commands.

That's been my experience for a while now. If others can confirm this experience , I think we should simply revert the utterance.

**Comment by kendonB** [comment]
I must have inadvertently deleted the branch - closing here

**Pull request closed without merging**
