### PR TITLE
add command named Dick for right-click

### PR DESCRIPTION
**Pull request by alexboche**
I'm assuming that the vertical bars don't mess up the latex I did not test it

### CODE REVIEW

**Comment by kendonB** [comment]
What's the use case for making this single syllable?

**Comment by alexboche** [comment]
typically selecting a word so something like "dick stoosh/deli/hug-quotes" . it's debatable whether it's worth a single syllable

**Comment by kendonB** [comment]
garb is already one of those. Given we already have "kick double" I don't really think it warrants a change. Others may disagree and I will try it out for a couple days

**Comment by LexiconCode** [comment]
One thing to note as well "Dick" is slang for male anatomy in America.  It just seems a bit awkward dictating.

**Comment by kendonB** [comment]
> One thing to note as well "Dick" is slang for male anatomy in America. It just seems a bit awkward dictating.

It would even be regarded as a curse word in some circles.

**Comment by LexiconCode** [comment]
Well besides the term being used are you finding functionality in a single syllable word?

**Comment by LexiconCode** [comment]
For now we will closes as should be able to be changed in words.txt

**Pull request closed without merging**
