### PR TITLE
Migrate Settings Window implementation from Wx to Qt

### PR DESCRIPTION
**Pull request by dmakarov**
## Description

This is first set of changes in the series of migrating GUI parts of Caster from Tk and Wx to Qt.
In this PR Settings Window GUI is reimplemented using Qt widgets of PySide2 package.

## Motivation and Context

Qt is currently the most advanced framework for GUI implementations.

## How Has This Been Tested

Tested by using Caster and invoking its command `launch settings window`

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue or bug)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Renamed existing command phrases (we discourage this without a strong rationale).

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] I have checked for and utilized existing command phrases from within Caster (delete if not applicable). 
- [ ] My code implements all the features I wish to merge in this pull request.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests pass.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [x] Code is clear and readable.

### CODE REVIEW

**Comment by LexiconCode** [comment]
As mentioned in chat QT is not preinstalled with Travis.
An update to travis.yml is required. A possible [resource](https://github.com/skalee/non-interactive-qt-installer/blob/master/.travis.yml)

**Comment by LexiconCode** [comment]
Thanks for this! Any help with Caster GUI is much appreciated.

As mentioned in chat the next step is to figure out how to manage QT in Travis and Python 2.

**Comment by dmakarov** [comment]
I think now this PR can be considered for reviewing.  Two versions of GUI coexist -- Qt- and Wx-based. If Qt (namely PySide2 package) is not available, Wx version is used.  Wx can be easily removed, once Qt becomes the _official_ Caster GUI framework. `Ctrl-Tab` and `Ctrl-Shift-Tab` keys can be used for circling over Setting tabs. `Tab` and `Shift-Tab` can be used to circle over individual fields used within a tab. Tested on macOS. It would be helpful, if someone tested this on Windows.

**Comment by LexiconCode** [comment]
I'll work through reviewing and testing this tomorrow.

**Comment by LexiconCode** [comment]
I tested this on Windows with Python 2.7.17 and 3.

Both GUIs launch is expected and look great. However on save there is an issue when the `complete` command is issued.

**(TK)** On save the configuration file becomes corrupt.
 
```toml
[Tree_Node_Path]

[formats]

[gitbash]

[grammar_reloading]

[hooks]

[miscellaneous]

[online]

[paths]

[python]

[sikuli]
```
**(QT)** `settings.toml` is not edited on save. 
```
ERROR:action:Exception from function hmc_settings_complete:
Traceback (most recent call last):
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\action_function.py", line 146, in _execute
    self._function(**arguments)
  File "D:\Backup\Library\Documents\Caster\castervoice\asynch\hmc_rules\hmc_settings_rule.py", line 10, in hmc_settings_complete
    control.nexus().comm.get_com("hmc").complete()
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\xmlrpc\client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\xmlrpc\client.py", line 1450, in __request
    response = self.__transport.request(
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\xmlrpc\client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\xmlrpc\client.py", line 1166, in single_request
    resp = http_conn.getresponse()
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
ERROR:action.exec:Execution failed: Function(hmc_settings_complete): Remote end closed connection without response
```

**Comment by LexiconCode** [comment]
via chat dmakarov provided some great debugging procedures. I wanted to make sure they were included the issue here for future reference.

>	`python castervoice/asynch/settingswindow.py` and in another shell start python, then execute the following commands:
```
$ python
Python 3.8.1 (default, Feb  9 2020, 17:32:11)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlrpc.client
>>> com = xmlrpc.client.ServerProxy("http://127.0.0.1:1338")
>>> com.complete()
>>> com.get_message()
```
>	if it works the dictionary (or json blob) of setting should be printed after the last command

**Comment by dmakarov** [comment]
The first of the errors should be fixed, that is wx version should work correctly on saving the settings.

**Comment by LexiconCode** [comment]
> ERROR:action.exec:Execution failed: Function(hmc_settings_complete): Remote end closed connection without response

I do not believe the Error above is strictly related to this PR I've been able to reproduce with mousegrid's the same issue.

**Comment by LexiconCode** [comment]
I can confirm across multiple machines that `Remote end closed connection without response` issue is with Python 3 and the Windows platform.

Awesome work and thank you again! @dmakarov

**Pull request merged**
