### PR TITLE
Caster settings.py rework

### PR DESCRIPTION
**Pull request by LexiconCode**
## Description

Overhauls various aspects of settings.py see details below.

## Related Issue

Resolves https://github.com/dictation-toolbox/Caster/issues/677

## Motivation and Context
**Separate caster data from end-user settings.**
Currently the `.caster/data` directory mixes data files at store caster related data (multi clipboard, record from history, alias and other features). These data files are not meant to be edited by the end-user. User facing Configuration files such as companion_config.toml, hooks.toml, settings.toml, and ... are meant to be modified by the end-user.

This pull request separates creates a new folder called `settings` where user facing configuration files are stored.

A debatable decision `sm_bringme.toml` has been included in the settings directory. This is easily edited to add new paths by keyboard by the end user. Storing it in the `data` directory would indicate it should only be editable by caster.

**Integrated modified version of Pathlib2 into Caster**

The file paths and settings.py utilize `os.path` which is not cross-platform and fragile. [Pathlib2](https://docs.python.org/dev/library/pathlib.html) handles conversions automatically and treats file paths as objects instead of strings. 

For now everything utilizes Pathlib2 converted to back to strings. This will change once file handling is fully supported across Caster by Pathlib2. The end result is a seamless transition to Python three which supports Pathlib and cross-platform file path handling. 

Due to encoding issues a modified version of Pathlib2 was integrated into Caster. will be removed once Python 2 support has been dropped from the CodeBase.

**Cross-platform User Directory using appdirs**
[AppDirs](https://pypi.org/project/appdirs/) Provide standard functions defining cross-platform storing user data. It is now stored in Local under Windows. This should reduce the issue of read/write permissions on locked down computers through work/academic environments.

`%USERNAME%\.caster` no longer used. Users `rule` directory should be manually transferred.
The new caster user directory `C:\Users\%USERNAME%\AppData\Local\caster`

**Updated BringMe Commands**
- BringMe defaults now leverage Pathlib
- BringMe commands now include updated 1.x.x commands
- BringMe command scheme for files follows `bring me caster <item> file` eg `bring me caster settings file` summons `settings.toml`
	- Helps differentiate between folders and files by the same name

**Minor Improvements**
- Converted print statements to `printer.out`
- Utilized `.format()` string formatting instead of Concatenation in settings.py

**Removeded**
 Removed a temporary piece of code to seamlessly migrate clipboards to JSON. 

## How Has This Been Tested

Deleting all configuration files and letting them regenerate within the appropriate folder structure. Also manually testing functions for produced file paths. Manually tested the Legion, workspace, and bring me to summon content.

## Types of changes

see above

**Note**: Deleting the data folder allows everything to generate as it should. Required for people updating once merged.

Items not to be included: Restructuring defaults out of and utilizing OOP in settings.py. Although recommended for the future.

- [x] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue or bug)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Renamed existing command phrases (we discourage this without a strong rationale).

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] I have checked that my code does not duplicate functionality elsewhere in Caster.
- [x] I have checked for and utilized existing command phrases from within Caster (delete if not applicable). 
- [x] My code implements all the features I wish to merge in this pull request. # Feedback needed
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. # ToDo
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests pass.

## Maintainer/Reviewer Checklist

- [ ] Basic functionality has been tested and works as claimed.
- [ ] New documentation is clear and complete.
- [ ] Code is clear and readable.

### CODE REVIEW

**Comment by LexiconCode** [comment]
@Versatilus you mentioned that the `data` files for caster should be stored outside of the caster user directory. Depending on your thoughts that could be implemented in this pull request.

**Comment by Versatilus** [comment]
This seems like an opportunity to deal with a few warts in the way we handle paths and some related things on Windows. There is a (relatively short, for a conference talk) video that goes over some of the rough spots in the way Python is used on Windows. The video is available at: https://www.youtube.com/watch?v=uoI57uMdDD4

I need to think about this for a while.

**Comment by LexiconCode** [comment]
newstr instead of str or unicode.

Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\Laptop\Documents\Caster\_caster.py", line 14, in <module>
    settings.initialize()
  File "C:\Users\Laptop\Documents\Caster\castervoice\lib\settings.py", line 485, in initialize
    _SETTINGS_PATH = str(Path(_USER_DIR).joinpath("settings/settings.toml"))
  File "C:\Python2\lib\site-packages\pathlib2\__init__.py", line 1260, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Python2\lib\site-packages\pathlib2\__init__.py", line 902, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Python2\lib\site-packages\pathlib2\__init__.py", line 895, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "C:\Python2\lib\site-packages\pathlib2\__init__.py", line 253, in parse_parts
    parsed.append(intern(rel))
TypeError: can't intern subclass of string

**Comment by Versatilus** [comment]
I'll see if I can reproduce that. It just might take a while.

**Comment by LexiconCode** [comment]
Due to encoding issues a modified version of Pathlib2 was integrated into Caster. will be removed once Python 2 support has been dropped from the CodeBase.

**Pull request merged**
