### PR TITLE
Update Sikuli 1.0.X to Sikulix 1.1.X.

### PR DESCRIPTION
**Pull request by LexiconCode**
Edit: Updated links to Sikulix 1.1.4 build and install. This version will be compatible with the upcoming release of SikuliX2.

Fixes path related issues related to changes in Sikulix from Sikuli.

**Install Sikulix**

1. Download [Sikulix.jar](https://raiman.github.io/SikuliX1/sikulix.jar) and [jython-standalone-2.7.1.jar](https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar). Then copy them in to a folder you'll have to create `C:\SikuliX`

capture

2. Click on `Sikulix.jar` as it should launch the Sikulix IDE. **Note**  `jython-standalone-2.7.1.jar` will disappear from `C:\SikuliX` folder. This is expected behavior on first-run of `Sikulix.jar`.

2. Add sikulix as instructed to `system variable` path. `SIKULI_HOME` `C:\SikuliX`

capture

3. Change SIKULI paths in settings.json
-  jre1.8.X or later must be installed and referenced in JAVA_EXE_PATH.
 ```
        "JAVA_EXE_PATH": "C:/Program Files/Java/jre1.8.0_181/bin/java.exe",
        "SIKULI_JAR_PATH": "C:/SikuliX/sikulix.jar",
        "SIKULI_SCRIPTS_FOLDER_PATH": "C:/NatLink/NatLink/MacroSystem/caster/asynch/sikuli/scripts",
        "SIKULI_SERVER_PATH": "C:/NatLink/NatLink/MacroSystem/caster/asynch/sikuli/scripts/xmlrpc_server.sikuli",
```
4. Change SIKULI `"sikuli_enabled"`  from _false_ to _true_ in settings.json
```
    "miscellaneous": {
        "sikuli_enabled": true
```

### CODE REVIEW

**Comment by Versatilus** [comment]
I'll try to test this out before the end of the coming weekend.

**Comment by LexiconCode** [comment]
The outstanding issues that I could use some help debugging.
- [ ] Grammar Sikuli commands not being loaded

> "launch sick IDE":                   Function(launch_IDE),
>         "launch sick server":        Function(launch_server),
>         "refresh sick you Lee":     Function(refresh_sick_command),
>         "sick shot":                       Key("cs-2"),

- [ ] Sikuli IDE not saving to the correct Caster script folder by default.

**Comment by LexiconCode** [comment]
I simplified the settings  "SIKULI_IDE_JAR_PATH" and "SIKULI_SCRIPTS_JAR_PATH are combined into "SIKULI_JAR_PATH" https://github.com/synkarius/caster/pull/215/commits/0c9eeaf049ef5244206f3bc3c4ebaf599d3a3d2f

The following setting may have depreciated as it's not referenced in the Castor project outside of settings.py/settings.json
`"SIKULI_SCRIPTS_FOLDER_PATH"

**Comment by LexiconCode** [comment]
I'm out of ideas.

**Comment by LexiconCode** [comment]
@Versatilus you been able to test?

**Comment by Versatilus** [comment]
I'm sorry about not responding to this earlier. I somehow missed this message. I haven't had a chance to test this yet. I've been having problems lately with my mental bandwidth and I need to get my act together. What issues did you run into when trying to run this with Java 9?

**Comment by LexiconCode** [comment]
@Versatilus No problem and thanks for getting back to me. I totally get the mental bandwidth some days I've got nothing. That being said I don't want to pressure you into contributing.

So the reason I stated to avoid Java 9 is because this message pops up from the IDE sikulix
> [info] IDE startup: 9.8 seconds
[info] ***** BE AWARE: Running on Java 9
[info] ... Please report problems *****

Looking at sikulix [issues](https://launchpad.net/sikuli/sikulix/1.1.2) Java 9 stability and is coming along.

**Comment by LexiconCode** [comment]
1.1.3 nightly build produces a new error.
2018-07-29_16h44_41

**Comment by LexiconCode** [comment]
Sikulix [1-1-4](https://sikulix-2014.readthedocs.io/en/latest/news.html#new-in-version-1-1-4) versions been released that has some significant changes.

**Comment by LexiconCode** [comment]
Sikulix 1.1.4 - 
1. Sikulix Commands work noting that the `example command` is supposed to find the Windows start menu for Windows 10. To test you _may_ need to [create your own](https://youtu.be/RFdsD2OgDzk?list=PLV6JPhkq1x8LHu02YefhUU9rXiB2PK8tc&t=342) Sikulix script. The grammar for Sikulix do not seem to function as its specs aren't recognized as commands.

The outstanding issue that I could use some help debugging.
- [ ] Grammar Sikuli does not seem to work and are not recognized as commands.

```
        "launch sick IDE":           Function(launch_IDE),
        "launch sick server":        Function(launch_server),
        "refresh sick you Lee":      Function(refresh_sick_command),
        "sick shot":                 Key("cs-2"),
```

[The relevant code in sikuli.py](https://github.com/LexiconCode/caster/blob/sikuli_update/caster/asynch/sikuli/sikuli.py#L80)

**Comment by LexiconCode** [comment]
Fulfilled by https://github.com/dictation-toolbox/caster/pull/374

**Pull request closed without merging**
